In [ ]:
!pip install sqlalchemy_mate==2.0.0.0

Requirement already satisfied: sqlalchemy_mate==2.0.0.0 in /usr/local/lib/python3.12/dist-packages (2.0.0.0)
Requirement already satisfied: sqlalchemy<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy_mate==2.0.0.0) (2.0.44)
Requirement already satisfied: prettytable<4.0.0,>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy_mate==2.0.0.0) (3.16.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable<4.0.0,>=3.0.0->sqlalchemy_mate==2.0.0.0) (0.2.14)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3.0.0,>=2.0.0->sqlalchemy_mate==2.0.0.0) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3.0.0,>=2.0.0->sqlalchemy_mate==2.0.0.0) (4.15.0)

In [ ]:
!pip install uszipcode

Requirement already satisfied: uszipcode in /usr/local/lib/python3.12/dist-packages (1.0.1)
Requirement already satisfied: attrs in /usr/local/lib/python3.12/dist-packages (from uszipcode) (25.4.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from uszipcode) (2.32.4)
Requirement already satisfied: pathlib-mate in /usr/local/lib/python3.12/dist-packages (from uszipcode) (1.3.2)
Requirement already satisfied: atomicwrites in /usr/local/lib/python3.12/dist-packages (from uszipcode) (1.4.1)
Requirement already satisfied: fuzzywuzzy in /usr/local/lib/python3.12/dist-packages (from uszipcode) (0.18.0)
Requirement already satisfied: haversine>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from uszipcode) (2.9.0)
Requirement already satisfied: SQLAlchemy>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from uszipcode) (2.0.44)
Requirement already satisfied: sqlalchemy-mate>=1.4.28.3 in /usr/local/lib/python3.12/dist-packages (from uszipcode) (2.0.0.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy>=1.4.0->uszipcode) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy>=1.4.0->uszipcode) (4.15.0)
Requirement already satisfied: prettytable<4.0.0,>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy-mate>=1.4.28.3->uszipcode) (3.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->uszipcode) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->uszipcode) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->uszipcode) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->uszipcode) (2025.10.5)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable<4.0.0,>=3.0.0->sqlalchemy-mate>=1.4.28.3->uszipcode) (0.2.14)

In [ ]:
from uszipcode import SearchEngine
search = SearchEngine()

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/CHAPA_Chapter-40B_Application-Data_2021-2025_merged_v0.1 - CHAPA_Chapter-40B_Application-Data_2021-2025_merged_v0.1 (1).csv')

In [ ]:
df['property_full_address'] = df['property_street_address'].astype(str) + ', ' + df['property_town_city'].astype(str) + ', ' + df['property_state'].astype(str)

In [ ]:
df['property_full_address'].head(15)

0     8 Ciderpress Way, North Andover, MA
1     8 Ciderpress Way, North Andover, MA
2     8 Ciderpress Way, North Andover, MA
3     8 Ciderpress Way, North Andover, MA
4     8 Ciderpress Way, North Andover, MA
5     8 Ciderpress Way, North Andover, MA
6           1301 Albion Road, Bedford, MA
7           1301 Albion Road, Bedford, MA
8           1301 Albion Road, Bedford, MA
9           1301 Albion Road, Bedford, MA
10          1301 Albion Road, Bedford, MA
11         65 Metacomet Ave., Taunton, MA
12         65 Metacomet Ave., Taunton, MA
13         65 Metacomet Ave., Taunton, MA
14          41 Boston Road, Billerica, MA
Name: property_full_address, dtype: object

In [ ]:
!pip install geopy

Requirement already satisfied: geopy in /usr/local/lib/python3.12/dist-packages (2.4.1)
Requirement already satisfied: geographiclib<3,>=1.52 in /usr/local/lib/python3.12/dist-packages (from geopy) (2.1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1739 entries, 0 to 1738
Data columns (total 31 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id_number                    1739 non-null   int64
 1   submission_date              1739 non-null   object
 2   age                          1739 non-null   int64
 3   disability                   1739 non-null   int64
 4   chapa_races                  1739 non-null   object
 5   hispanic_latino              380 non-null    float64
 6   census_races                 1739 non-null   object
 7   current_residence_town_city  1739 non-null   object
 8   current_residence_state      1739 non-null   object
 9   current_residence_zip        0 non-null      float64
 10  application_source           1739 non-null   object
 11  hh_size                      1739 non-null   int64
 12  dependents                   1621 non-null   float64
 13  hh_type                      1739 non-null   object
 14  hh_income                    1732 non-null   object
 15  hh_assets                    1716 non-null   object
 16  income_bracket               380 non-null    object
 17  asset_bracket                380 non-null    object
 18  unique_id                    1359 non-null   float64
 19  property_full_address        1739 non-null   object
 20  property_street_address      1739 non-null   object
 21  property_unit                786 non-null    object
 22  property_town_city           1739 non-null   object
 23  property_state               1739 non-null   object
 24  property_zip                 0 non-null      float64
 25  match_status                 1739 non-null   object
 26  match_type                   1589 non-null   object
 27  matched_address              1589 non-null   object
 28  fthb_class                   1739 non-null   int64
 29  msa                          1739 non-null   object
 30  property_restriction         70 non-null     object
dtypes: float64(5), int64(5), object(21)
memory usage: 421.3+ KB

# property zip, lat, lon, population

In [ ]:
property_lat = [0 for i in range(len(df))]
property_lon = [0 for i in range(len(df))]
property_town_population = [0 for i in range(len(df))]

In [ ]:
town_missing = []

for i in range(len(df)):

  town_name = df['property_town_city'][i]
  state_abbr = df['property_state'][i]

  results = search.by_city_and_state(city=town_name, state=state_abbr, returns=0)

  if results:
    sorted_zips = sorted(
        results,
        key = lambda x : x.population if x.population is not None else -1,
        reverse = True
    )

    selected_zip = sorted_zips[0]

    zip_code = selected_zip.zipcode
    latitude = selected_zip.lat
    longitude = selected_zip.lng
    population = selected_zip.population

    df['property_zip'][i] = zip_code
    property_lat[i] = latitude
    property_lon[i] = longitude
    property_town_population[i] = population

    print(f"--- {i}. {town_name}, {state_abbr} ({len(results)})---")
    print(f"ZIP: {zip_code} | Lat/Lon: {latitude}, {longitude} | Population: {population}")

  else:
    print(f"'{i}, {town_name}, {state_abbr}' could not be find")
    town_missing.append(i)

/tmp/ipython-input-85318812.py:24: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['property_zip'][i] = zip_code
/tmp/ipython-input-85318812.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['property_zip'][i] = zip_code
/tmp/ipython-input-85318812.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '01845' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['property_zip'][i] = zip_code

--- 0. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 1. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 2. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 3. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 4. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 5. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 6. Bedford, MA (1)---
ZIP: 01730 | Lat/Lon: 42.48, -71.26 | Population: 13221
--- 7. Bedford, MA (1)---
ZIP: 01730 | Lat/Lon: 42.48, -71.26 | Population: 13221
--- 8. Bedford, MA (1)---
ZIP: 01730 | Lat/Lon: 42.48, -71.26 | Population: 13221
--- 9. Bedford, MA (1)---
ZIP: 01730 | Lat/Lon: 42.48, -71.26 | Population: 13221
--- 10. Bedford, MA (1)---
ZIP: 01730 | Lat/Lon: 42.48, -71.26 | Population: 13221
--- 11. Taunton, MA (1)---
ZIP: 02780 | Lat/Lon: 41.9, -71.09 | Population: 49036
--- 12. Taunton, MA (1)---
ZIP: 02780 | Lat/Lon: 41.9, -71.09 | Population: 49036
--- 13. Taunton, MA (1)---
ZIP: 02780 | Lat/Lon: 41.9, -71.09 | Population: 49036
--- 14. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 15. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 16. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 17. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 18. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 19. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 20. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 21. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 22. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 23. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 24. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 25. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 26. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 27. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 28. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 29. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 30. Ipswich, MA (1)---
ZIP: 01938 | Lat/Lon: 42.67, -70.83 | Population: 13175
--- 31. Ipswich, MA (1)---
ZIP: 01938 | Lat/Lon: 42.67, -70.83 | Population: 13175
--- 32. Ipswich, MA (1)---
ZIP: 01938 | Lat/Lon: 42.67, -70.83 | Population: 13175
--- 33. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 34. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 35. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 36. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 37. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 38. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 39. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 40. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 41. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 42. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 43. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 44. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 45. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 46. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 47. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 48. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 49. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 50. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 51. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 52. Medway, MA (1)---
ZIP: 02053 | Lat/Lon: 42.16, -71.43 | Population: 12752
--- 53. Medway, MA (1)---
ZIP: 02053 | Lat/Lon: 42.16, -71.43 | Population: 12752
--- 54. Medway, MA (1)---
ZIP: 02053 | Lat/Lon: 42.16, -71.43 | Population: 12752
--- 55. Medway, MA (1)---
ZIP: 02053 | Lat/Lon: 42.16, -71.43 | Population: 12752
--- 56. Medway, MA (1)---
ZIP: 02053 | Lat/Lon: 42.16, -71.43 | Population: 12752
--- 57. Medway, MA (1)---
ZIP: 02053 | Lat/Lon: 42.16, -71.43 | Population: 12752
--- 58. Medway, MA (1)---
ZIP: 02053 | Lat/Lon: 42.16, -71.43 | Population: 12752
--- 59. Medway, MA (1)---
ZIP: 02053 | Lat/Lon: 42.16, -71.43 | Population: 12752
--- 60. Medway, MA (1)---
ZIP: 02053 | Lat/Lon: 42.16, -71.43 | Population: 12752
--- 61. Merrimac, MA (1)---
ZIP: 01860 | Lat/Lon: 42.83, -71.0 | Population: 6338
--- 62. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 63. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 64. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 65. Braintree, MA (1)---
ZIP: 02184 | Lat/Lon: 42.2, -71.0 | Population: 35744
--- 66. Braintree, MA (1)---
ZIP: 02184 | Lat/Lon: 42.2, -71.0 | Population: 35744
--- 67. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 68. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 69. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 70. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 71. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 72. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 73. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 74. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 75. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 76. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 77. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 78. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 79. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 80. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 81. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 82. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 83. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 84. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 85. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 86. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 87. Sturbridge, MA (1)---
ZIP: 01566 | Lat/Lon: 42.09, -72.06 | Population: 6294
'88, Hamilton, MA' could not be find
'89, Hamilton, MA' could not be find
'90, Hamilton, MA' could not be find
'91, Hamilton, MA' could not be find
'92, Hamilton, MA' could not be find
'93, Hamilton, MA' could not be find
'94, Hamilton, MA' could not be find
--- 95. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 96. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 97. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 98. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 99. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 100. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 101. Marblehead, MA (1)---
ZIP: 01945 | Lat/Lon: 42.5, -70.85 | Population: 19808
--- 102. Marblehead, MA (1)---
ZIP: 01945 | Lat/Lon: 42.5, -70.85 | Population: 19808
--- 103. Marblehead, MA (1)---
ZIP: 01945 | Lat/Lon: 42.5, -70.85 | Population: 19808
--- 104. Marblehead, MA (1)---
ZIP: 01945 | Lat/Lon: 42.5, -70.85 | Population: 19808
--- 105. Marblehead, MA (1)---
ZIP: 01945 | Lat/Lon: 42.5, -70.85 | Population: 19808
--- 106. Marblehead, MA (1)---
ZIP: 01945 | Lat/Lon: 42.5, -70.85 | Population: 19808
--- 107. Methuen, MA (1)---
ZIP: 01844 | Lat/Lon: 42.74, -71.18 | Population: 47249
--- 108. Methuen, MA (1)---
ZIP: 01844 | Lat/Lon: 42.74, -71.18 | Population: 47249
--- 109. Methuen, MA (1)---
ZIP: 01844 | Lat/Lon: 42.74, -71.18 | Population: 47249
--- 110. Methuen, MA (1)---
ZIP: 01844 | Lat/Lon: 42.74, -71.18 | Population: 47249
--- 111. Methuen, MA (1)---
ZIP: 01844 | Lat/Lon: 42.74, -71.18 | Population: 47249
--- 112. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 113. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 114. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 115. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 116. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 117. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 118. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 119. Tyngsborough, MA (1)---
ZIP: 01879 | Lat/Lon: 42.68, -71.41 | Population: 11305
--- 120. Tyngsborough, MA (1)---
ZIP: 01879 | Lat/Lon: 42.68, -71.41 | Population: 11305
--- 121. Tyngsborough, MA (1)---
ZIP: 01879 | Lat/Lon: 42.68, -71.41 | Population: 11305
--- 122. Tyngsborough, MA (1)---
ZIP: 01879 | Lat/Lon: 42.68, -71.41 | Population: 11305
--- 123. Tyngsborough, MA (1)---
ZIP: 01879 | Lat/Lon: 42.68, -71.41 | Population: 11305
--- 124. Tyngsborough, MA (1)---
ZIP: 01879 | Lat/Lon: 42.68, -71.41 | Population: 11305
--- 125. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 126. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 127. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 128. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 129. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 130. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 131. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 132. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 133. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 134. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 135. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 136. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 137. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 138. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 139. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 140. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 141. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 142. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 143. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 144. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 145. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 146. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 147. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 148. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 149. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 150. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 151. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 152. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 153. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 154. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 155. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 156. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 157. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 158. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 159. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 160. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 161. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 162. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 163. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 164. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 165. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 166. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 167. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 168. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 169. North Reading, MA (1)---
ZIP: 01864 | Lat/Lon: 42.58, -71.08 | Population: 14892
--- 170. North Reading, MA (1)---
ZIP: 01864 | Lat/Lon: 42.58, -71.08 | Population: 14892
--- 171. Carlisle, MA (1)---
ZIP: 01741 | Lat/Lon: 42.53, -71.35 | Population: 4852
--- 172. Carlisle, MA (1)---
ZIP: 01741 | Lat/Lon: 42.53, -71.35 | Population: 4852
--- 173. Carlisle, MA (1)---
ZIP: 01741 | Lat/Lon: 42.53, -71.35 | Population: 4852
--- 174. Carlisle, MA (1)---
ZIP: 01741 | Lat/Lon: 42.53, -71.35 | Population: 4852
--- 175. Carlisle, MA (1)---
ZIP: 01741 | Lat/Lon: 42.53, -71.35 | Population: 4852
--- 176. Carlisle, MA (1)---
ZIP: 01741 | Lat/Lon: 42.53, -71.35 | Population: 4852
--- 177. Carlisle, MA (1)---
ZIP: 01741 | Lat/Lon: 42.53, -71.35 | Population: 4852
--- 178. Carlisle, MA (1)---
ZIP: 01741 | Lat/Lon: 42.53, -71.35 | Population: 4852
--- 179. Carlisle, MA (1)---
ZIP: 01741 | Lat/Lon: 42.53, -71.35 | Population: 4852
--- 180. Carlisle, MA (1)---
ZIP: 01741 | Lat/Lon: 42.53, -71.35 | Population: 4852
--- 181. Carlisle, MA (1)---
ZIP: 01741 | Lat/Lon: 42.53, -71.35 | Population: 4852
--- 182. Carlisle, MA (1)---
ZIP: 01741 | Lat/Lon: 42.53, -71.35 | Population: 4852
--- 183. Carlisle, MA (1)---
ZIP: 01741 | Lat/Lon: 42.53, -71.35 | Population: 4852
--- 184. Groveland, MA (1)---
ZIP: 01834 | Lat/Lon: 42.75, -71.03 | Population: 6459
--- 185. Groveland, MA (1)---
ZIP: 01834 | Lat/Lon: 42.75, -71.03 | Population: 6459
--- 186. Groveland, MA (1)---
ZIP: 01834 | Lat/Lon: 42.75, -71.03 | Population: 6459
--- 187. Groveland, MA (1)---
ZIP: 01834 | Lat/Lon: 42.75, -71.03 | Population: 6459
--- 188. Groveland, MA (1)---
ZIP: 01834 | Lat/Lon: 42.75, -71.03 | Population: 6459
--- 189. Groveland, MA (1)---
ZIP: 01834 | Lat/Lon: 42.75, -71.03 | Population: 6459
--- 190. Groveland, MA (1)---
ZIP: 01834 | Lat/Lon: 42.75, -71.03 | Population: 6459
--- 191. Groveland, MA (1)---
ZIP: 01834 | Lat/Lon: 42.75, -71.03 | Population: 6459
--- 192. Groveland, MA (1)---
ZIP: 01834 | Lat/Lon: 42.75, -71.03 | Population: 6459
--- 193. Groveland, MA (1)---
ZIP: 01834 | Lat/Lon: 42.75, -71.03 | Population: 6459
--- 194. Milford, MA (1)---
ZIP: 01757 | Lat/Lon: 42.14, -71.51 | Population: 28061
--- 195. Milford, MA (1)---
ZIP: 01757 | Lat/Lon: 42.14, -71.51 | Population: 28061
--- 196. Milford, MA (1)---
ZIP: 01757 | Lat/Lon: 42.14, -71.51 | Population: 28061
--- 197. Milford, MA (1)---
ZIP: 01757 | Lat/Lon: 42.14, -71.51 | Population: 28061
--- 198. Milford, MA (1)---
ZIP: 01757 | Lat/Lon: 42.14, -71.51 | Population: 28061
--- 199. Taunton, MA (1)---
ZIP: 02780 | Lat/Lon: 41.9, -71.09 | Population: 49036
--- 200. Taunton, MA (1)---
ZIP: 02780 | Lat/Lon: 41.9, -71.09 | Population: 49036
--- 201. Taunton, MA (1)---
ZIP: 02780 | Lat/Lon: 41.9, -71.09 | Population: 49036
--- 202. Harvard, MA (1)---
ZIP: 01451 | Lat/Lon: 42.5, -71.58 | Population: 4747
--- 203. Harvard, MA (1)---
ZIP: 01451 | Lat/Lon: 42.5, -71.58 | Population: 4747
--- 204. Harvard, MA (1)---
ZIP: 01451 | Lat/Lon: 42.5, -71.58 | Population: 4747
--- 205. Lancaster, MA (1)---
ZIP: 01523 | Lat/Lon: 42.45, -71.66 | Population: 7582
--- 206. Methuen, MA (1)---
ZIP: 01844 | Lat/Lon: 42.74, -71.18 | Population: 47249
--- 207. Methuen, MA (1)---
ZIP: 01844 | Lat/Lon: 42.74, -71.18 | Population: 47249
--- 208. Easthampton, MA (1)---
ZIP: 01027 | Lat/Lon: 42.26, -72.68 | Population: 17660
--- 209. Easthampton, MA (1)---
ZIP: 01027 | Lat/Lon: 42.26, -72.68 | Population: 17660
--- 210. Norton, MA (1)---
ZIP: 02766 | Lat/Lon: 41.96, -71.18 | Population: 19031
--- 211. Norton, MA (1)---
ZIP: 02766 | Lat/Lon: 41.96, -71.18 | Population: 19031
--- 212. Norton, MA (1)---
ZIP: 02766 | Lat/Lon: 41.96, -71.18 | Population: 19031
--- 213. Norton, MA (1)---
ZIP: 02766 | Lat/Lon: 41.96, -71.18 | Population: 19031
--- 214. Norton, MA (1)---
ZIP: 02766 | Lat/Lon: 41.96, -71.18 | Population: 19031
--- 215. Norton, MA (1)---
ZIP: 02766 | Lat/Lon: 41.96, -71.18 | Population: 19031
--- 216. Norton, MA (1)---
ZIP: 02766 | Lat/Lon: 41.96, -71.18 | Population: 19031
--- 217. Norton, MA (1)---
ZIP: 02766 | Lat/Lon: 41.96, -71.18 | Population: 19031
--- 218. Norton, MA (1)---
ZIP: 02766 | Lat/Lon: 41.96, -71.18 | Population: 19031
--- 219. Norton, MA (1)---
ZIP: 02766 | Lat/Lon: 41.96, -71.18 | Population: 19031
--- 220. Ayer, MA (1)---
ZIP: 01432 | Lat/Lon: 42.56, -71.58 | Population: 7089
--- 221. Ayer, MA (1)---
ZIP: 01432 | Lat/Lon: 42.56, -71.58 | Population: 7089
--- 222. Ayer, MA (1)---
ZIP: 01432 | Lat/Lon: 42.56, -71.58 | Population: 7089
--- 223. Ayer, MA (1)---
ZIP: 01432 | Lat/Lon: 42.56, -71.58 | Population: 7089
--- 224. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 225. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 226. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 227. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 228. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 229. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 230. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 231. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 232. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 233. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 234. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 235. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 236. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 237. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 238. North Andover, MA (1)---

In [ ]:
df['property_lat'] = property_lat
df['property_lon'] = property_lon
df['property_town_population'] = property_town_population

# currnet zip, lat, lon, population

In [ ]:
current_lat = [0 for i in range(len(df))]
current_lon = [0 for i in range(len(df))]
current_town_population = [0 for i in range(len(df))]

In [ ]:
print(df['current_residence_town_city'][496])
print(df['current_residence_town_city'][497])
print(df['current_residence_town_city'][1297])
print(df['current_residence_town_city'][1723])

Pelham
Pelham
Pelham
Bristol County

In [ ]:
town_drop = [496, 497, 1297, 1723]
town_missing = []

for i in range(len(df)):
  if i in town_drop:
    continue

  town_name = df['current_residence_town_city'][i]
  state_abbr = df['current_residence_state'][i]

  if town_name == 'Unknown':
    continue

  results = search.by_city_and_state(city=town_name, state=state_abbr, returns=0)

  if results:
    sorted_zips = sorted(
        results,
        key = lambda x : x.population if x.population is not None else -1,
        reverse = True
    )

    selected_zip = sorted_zips[0]

    zip_code = selected_zip.zipcode
    latitude = selected_zip.lat
    longitude = selected_zip.lng
    population = selected_zip.population

    df['current_residence_zip'][i] = zip_code
    current_lat[i] = latitude
    current_lon[i] = longitude
    current_town_population[i] = population

    print(f"--- {i}. {town_name}, {state_abbr} ({len(results)})---")
    print(f"ZIP: {zip_code} | Lat/Lon: {latitude}, {longitude} | Population: {population}")

  else:
    print(f"'{i}, {town_name}, {state_abbr}' could not be find")
    town_missing.append(i)

--- 0. Somerville, MA (3)---
ZIP: 02145 | Lat/Lon: 42.39, -71.1 | Population: 25439

/tmp/ipython-input-3176788376.py:30: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['current_residence_zip'][i] = zip_code
/tmp/ipython-input-3176788376.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['current_residence_zip'][i] = zip_code
/tmp/ipython-input-3176788376.py:30: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '02145' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['current_residence_zip'][i] = zip_code

--- 1. Westford, MA (1)---
ZIP: 01886 | Lat/Lon: 42.58, -71.43 | Population: 21951
--- 2. Malden, MA (1)---
ZIP: 02148 | Lat/Lon: 42.43, -71.05 | Population: 59503
--- 3. Haverhill, MA (3)---
ZIP: 01830 | Lat/Lon: 42.78, -71.08 | Population: 25137
--- 4. Nashua, NH (4)---
ZIP: 03060 | Lat/Lon: 42.74, -71.46 | Population: 29357
--- 5. East Boston, MA (1)---
ZIP: 02128 | Lat/Lon: 42.36, -71.01 | Population: 40508
--- 6. Waltham, MA (3)---
ZIP: 02453 | Lat/Lon: 42.37, -71.24 | Population: 28968
--- 7. Woburn, MA (1)---
ZIP: 01801 | Lat/Lon: 42.48, -71.15 | Population: 38903
--- 8. Woburn, MA (1)---
ZIP: 01801 | Lat/Lon: 42.48, -71.15 | Population: 38903
--- 9. Burlington, MA (1)---
ZIP: 01803 | Lat/Lon: 42.5, -71.2 | Population: 24487
--- 10. Chelmsford, MA (1)---
ZIP: 01824 | Lat/Lon: 42.59, -71.36 | Population: 24911
--- 11. Mansfield, MA (1)---
ZIP: 02048 | Lat/Lon: 42.02, -71.21 | Population: 23184
--- 12. Taunton, MA (1)---
ZIP: 02780 | Lat/Lon: 41.9, -71.09 | Population: 49036
--- 13. Taunton, MA (1)---
ZIP: 02780 | Lat/Lon: 41.9, -71.09 | Population: 49036
--- 14. Burlington, MA (1)---
ZIP: 01803 | Lat/Lon: 42.5, -71.2 | Population: 24487
--- 15. Woburn, MA (1)---
ZIP: 01801 | Lat/Lon: 42.48, -71.15 | Population: 38903
--- 16. Waltham, MA (3)---
ZIP: 02453 | Lat/Lon: 42.37, -71.24 | Population: 28968
--- 17. Beverly, MA (1)---
ZIP: 01915 | Lat/Lon: 42.57, -70.87 | Population: 39502
--- 18. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 19. Burlington, MA (1)---
ZIP: 01803 | Lat/Lon: 42.5, -71.2 | Population: 24487
--- 20. Woburn, MA (1)---
ZIP: 01801 | Lat/Lon: 42.48, -71.15 | Population: 38903
--- 21. Lawrence, MA (3)---
ZIP: 01841 | Lat/Lon: 42.71, -71.16 | Population: 47225
--- 22. Woburn, MA (1)---
ZIP: 01801 | Lat/Lon: 42.48, -71.15 | Population: 38903
--- 23. Reading, MA (1)---
ZIP: 01867 | Lat/Lon: 42.53, -71.1 | Population: 23956
--- 24. Reading, MA (1)---
ZIP: 01867 | Lat/Lon: 42.53, -71.1 | Population: 23956
--- 25. Tyngsboro, MA (1)---
ZIP: 01879 | Lat/Lon: 42.68, -71.41 | Population: 11305
--- 26. Bedford, MA (1)---
ZIP: 01730 | Lat/Lon: 42.48, -71.26 | Population: 13221
--- 27. Bedford, MA (1)---
ZIP: 01730 | Lat/Lon: 42.48, -71.26 | Population: 13221
--- 28. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 29. Lawrence, MA (3)---
ZIP: 01841 | Lat/Lon: 42.71, -71.16 | Population: 47225
--- 30. Ipswich, MA (1)---
ZIP: 01938 | Lat/Lon: 42.67, -70.83 | Population: 13175
--- 31. Ipswich, MA (1)---
ZIP: 01938 | Lat/Lon: 42.67, -70.83 | Population: 13175
--- 32. Ipswich, MA (1)---
ZIP: 01938 | Lat/Lon: 42.67, -70.83 | Population: 13175
--- 33. Middleborough, MA (1)---
ZIP: 02346 | Lat/Lon: 41.86, -70.9 | Population: 23106
--- 34. Stoneham, MA (1)---
ZIP: 02180 | Lat/Lon: 42.47, -71.09 | Population: 21437
--- 35. Somerville, MA (3)---
ZIP: 02145 | Lat/Lon: 42.39, -71.1 | Population: 25439
--- 36. Haverhill, MA (3)---
ZIP: 01830 | Lat/Lon: 42.78, -71.08 | Population: 25137
--- 37. Saugus, MA (1)---
ZIP: 01906 | Lat/Lon: 42.46, -71.01 | Population: 26660
--- 38. Saugus, MA (1)---
ZIP: 01906 | Lat/Lon: 42.46, -71.01 | Population: 26660
--- 39. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 40. Malden, MA (1)---
ZIP: 02148 | Lat/Lon: 42.43, -71.05 | Population: 59503
--- 41. Dracut, MA (1)---
ZIP: 01826 | Lat/Lon: 42.68, -71.3 | Population: 29422
--- 42. Lawrence, MA (3)---
ZIP: 01841 | Lat/Lon: 42.71, -71.16 | Population: 47225
--- 43. Dracut, MA (1)---
ZIP: 01826 | Lat/Lon: 42.68, -71.3 | Population: 29422
--- 44. Andover, MA (1)---
ZIP: 01810 | Lat/Lon: 42.65, -71.14 | Population: 33201
--- 45. Nashua, NH (4)---
ZIP: 03060 | Lat/Lon: 42.74, -71.46 | Population: 29357
--- 46. Cape Coral, FL (6)---
ZIP: 33914 | Lat/Lon: 26.55, -82.02 | Population: 35848
--- 47. Topsfield, MA (1)---
ZIP: 01983 | Lat/Lon: 42.63, -70.95 | Population: 6089
--- 48. Chester, NH (1)---
ZIP: 03036 | Lat/Lon: 42.95, -71.25 | Population: 4782
--- 49. North Reading, MA (1)---
ZIP: 01864 | Lat/Lon: 42.58, -71.08 | Population: 14892
--- 50. Andover, MA (1)---
ZIP: 01810 | Lat/Lon: 42.65, -71.14 | Population: 33201
--- 51. Revere, MA (1)---
ZIP: 02151 | Lat/Lon: 42.41, -70.99 | Population: 51808
--- 52. Bellingham, MA (1)---
ZIP: 02019 | Lat/Lon: 42.09, -71.47 | Population: 16332
--- 53. North Attleborough, MA (1)---
ZIP: 02760 | Lat/Lon: 41.97, -71.33 | Population: 26739
--- 54. Plainville, MA (1)---
ZIP: 02762 | Lat/Lon: 42.0, -71.33 | Population: 8264
--- 55. Medway, MA (1)---
ZIP: 02053 | Lat/Lon: 42.16, -71.43 | Population: 12752
--- 56. Medway, MA (1)---
ZIP: 02053 | Lat/Lon: 42.16, -71.43 | Population: 12752
--- 57. Uxbridge, MA (1)---
ZIP: 01569 | Lat/Lon: 42.08, -71.6 | Population: 13569
--- 58. Medway, MA (1)---
ZIP: 02053 | Lat/Lon: 42.16, -71.43 | Population: 12752
--- 59. Franklin, MA (1)---
ZIP: 02038 | Lat/Lon: 42.08, -71.38 | Population: 31635
--- 60. Ashland, MA (1)---
ZIP: 01721 | Lat/Lon: 42.25, -71.46 | Population: 16593
--- 61. Newburyport, MA (1)---
ZIP: 01950 | Lat/Lon: 42.81, -70.88 | Population: 17416
--- 62. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 63. Dracut, MA (1)---
ZIP: 01826 | Lat/Lon: 42.68, -71.3 | Population: 29422
--- 64. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 65. Watertown, MA (1)---
ZIP: 02472 | Lat/Lon: 42.37, -71.18 | Population: 32014
--- 66. Dorchester, MA (3)---
ZIP: 02125 | Lat/Lon: 42.32, -71.06 | Population: 33295
--- 67. Peabody, MA (1)---
ZIP: 01960 | Lat/Lon: 42.53, -70.97 | Population: 50944
--- 68. Salem, MA (1)---
ZIP: 01970 | Lat/Lon: 42.51, -70.9 | Population: 41109
--- 69. Andover, MA (1)---
ZIP: 01810 | Lat/Lon: 42.65, -71.14 | Population: 33201
--- 70. Burlington, MA (1)---
ZIP: 01803 | Lat/Lon: 42.5, -71.2 | Population: 24487
--- 71. Derry, NH (1)---
ZIP: 03038 | Lat/Lon: 42.89, -71.28 | Population: 33269
--- 72. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 73. Woburn, MA (1)---
ZIP: 01801 | Lat/Lon: 42.48, -71.15 | Population: 38903
--- 74. Stoughton, MA (1)---
ZIP: 02072 | Lat/Lon: 42.11, -71.1 | Population: 26999
--- 75. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 76. Hyde Park, MA (1)---
ZIP: 02136 | Lat/Lon: 42.26, -71.13 | Population: 28488
--- 77. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 78. North Attleborough, MA (1)---
ZIP: 02760 | Lat/Lon: 41.97, -71.33 | Population: 26739
--- 79. Quincy, MA (3)---
ZIP: 02169 | Lat/Lon: 42.26, -71.0 | Population: 55055
--- 80. Hyde Park, MA (1)---
ZIP: 02136 | Lat/Lon: 42.26, -71.13 | Population: 28488
--- 82. Reading, MA (1)---
ZIP: 01867 | Lat/Lon: 42.53, -71.1 | Population: 23956
--- 83. Somerville, MA (3)---
ZIP: 02145 | Lat/Lon: 42.39, -71.1 | Population: 25439
--- 84. Andover, MA (1)---
ZIP: 01810 | Lat/Lon: 42.65, -71.14 | Population: 33201
--- 85. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 86. Woburn, MA (1)---
ZIP: 01801 | Lat/Lon: 42.48, -71.15 | Population: 38903
--- 87. Westminster, MA (1)---
ZIP: 01473 | Lat/Lon: 42.55, -71.9 | Population: 7277
--- 88. Everett, MA (1)---
ZIP: 02149 | Lat/Lon: 42.4, -71.05 | Population: 41550
--- 89. Peabody, MA (1)---
ZIP: 01960 | Lat/Lon: 42.53, -70.97 | Population: 50944
--- 90. Beverly, MA (1)---
ZIP: 01915 | Lat/Lon: 42.57, -70.87 | Population: 39502
--- 91. Beverly, MA (1)---
ZIP: 01915 | Lat/Lon: 42.57, -70.87 | Population: 39502
--- 92. Beverly, MA (1)---
ZIP: 01915 | Lat/Lon: 42.57, -70.87 | Population: 39502
--- 93. Beverly, MA (1)---
ZIP: 01915 | Lat/Lon: 42.57, -70.87 | Population: 39502
--- 94. Lowell, MA (4)---
ZIP: 01852 | Lat/Lon: 42.63, -71.3 | Population: 33508
--- 95. Woburn, MA (1)---
ZIP: 01801 | Lat/Lon: 42.48, -71.15 | Population: 38903
--- 96. Woburn, MA (1)---
ZIP: 01801 | Lat/Lon: 42.48, -71.15 | Population: 38903
--- 97. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 99. Andover, MA (1)---
ZIP: 01810 | Lat/Lon: 42.65, -71.14 | Population: 33201
--- 100. Haverhill, MA (3)---
ZIP: 01830 | Lat/Lon: 42.78, -71.08 | Population: 25137
--- 101. Marblehead, MA (1)---
ZIP: 01945 | Lat/Lon: 42.5, -70.85 | Population: 19808
--- 102. Boston, MA (16)---
ZIP: 02115 | Lat/Lon: 42.34, -71.1 | Population: 28441
--- 103. Marblehead, MA (1)---
ZIP: 01945 | Lat/Lon: 42.5, -70.85 | Population: 19808
--- 104. Melrose, MA (1)---
ZIP: 02176 | Lat/Lon: 42.45, -71.05 | Population: 26983
--- 105. Beverly, MA (1)---
ZIP: 01915 | Lat/Lon: 42.57, -70.87 | Population: 39502
--- 106. Swampscott, MA (1)---
ZIP: 01907 | Lat/Lon: 42.47, -70.91 | Population: 14027
--- 107. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11 | Population: 28352
--- 108. Lowell, MA (4)---
ZIP: 01852 | Lat/Lon: 42.63, -71.3 | Population: 33508
--- 109. Wilmington, MA (1)---
ZIP: 01887 | Lat/Lon: 42.55, -71.16 | Population: 22325
--- 110. Andover, MA (1)---
ZIP: 01810 | Lat/Lon: 42.65, -71.14 | Population: 33201
--- 111. Stow, MA (1)---
ZIP: 01775 | Lat/Lon: 42.43, -71.5 | Population: 6590
--- 112. Arlington, MA (2)---
ZIP: 02474 | Lat/Lon: 42.42, -71.16 | Population: 26312
--- 113. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 114. Nashua, NH (4)---
ZIP: 03060 | Lat/Lon: 42.74, -71.46 | Population: 29357
--- 115. Tewksbury, MA (1)---
ZIP: 01876 | Lat/Lon: 42.61, -71.23 | Population: 28667
--- 116. Quincy, MA (3)---
ZIP: 02169 | Lat/Lon: 42.26, -71.0 | Population: 55055
--- 117. North Billerica, MA (1)---
ZIP: 01862 | Lat/Lon: 42.58, -71.3 | Population: 10227
--- 118. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 119. Wakefield, MA (1)---
ZIP: 01880 | Lat/Lon: 42.5, -71.06 | Population: 24733
--- 120. Revere, MA (1)---
ZIP: 02151 | Lat/Lon: 42.41, -70.99 | Population: 51808
--- 121. Malden, MA (1)---
ZIP: 02148 | Lat/Lon: 42.43, -71.05 | Population: 59503
--- 122. Stow, MA (1)---
ZIP: 01775 | Lat/Lon: 42.43, -71.5 | Population: 6590
--- 123. Lowell, MA (4)---
ZIP: 01852 | Lat/Lon: 42.63, -71.3 | Population: 33508
--- 124. Lowell, MA (4)---
ZIP: 01852 | Lat/Lon: 42.63, -71.3 | Population: 33508
--- 125. Roslindale, MA (1)---
ZIP: 02131 | Lat/Lon: 42.28, -71.13 | Population: 29826
--- 126. Weymouth, MA (1)---
ZIP: 02188 | Lat/Lon: 42.2, -70.96 | Population: 14608
--- 128. Medford, MA (1)---
ZIP: 02155 | Lat/Lon: 42.42, -71.1 | Population: 57964
--- 129. Foxboro, MA (1)---
ZIP: 02035 | Lat/Lon: 42.06, -71.24 | Population: 16865
--- 130. Brockton, MA (2)---
ZIP: 02301 | Lat/Lon: 42.08, -71.02 | Population: 61025
--- 131. West Roxbury, MA (1)---
ZIP: 02132 | Lat/Lon: 42.28, -71.16 | Population: 25861
--- 132. Norwood, MA (1)---
ZIP: 02062 | Lat/Lon: 42.18, -71.19 | Population: 28602
--- 133. Quincy, MA (3)---
ZIP: 02169 | Lat/Lon: 42.26, -71.0 | Population: 55055
--- 134. Dedham, MA (1)---
ZIP: 02026 | Lat/Lon: 42.24, -71.17 | Population: 24711
--- 135. Worcester, MA (10)---
ZIP: 01604 | Lat/Lon: 42.25, -71.77 | Population: 34677
--- 136. Quincy, MA (3)---
ZIP: 02169 | Lat/Lon: 42.26, -71.0 | Population: 55055
--- 137. Brookline, MA (2)---
ZIP: 02446 | Lat/Lon: 42.34, -71.12 | Population: 29311
--- 138. Quincy, MA (3)---
ZIP: 02169 | Lat/Lon: 42.26, -71.0 | Population: 55055
--- 139. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 140. Taunton, MA (1)---
ZIP: 02780 | Lat/Lon: 41.9, -71.09 | Population: 49036
--- 141. Hyde Park, MA (1)---
ZIP: 02136 | Lat/Lon: 42.26, -71.13 | Population: 28488
--- 142. Dedham, MA (1)---
ZIP: 02026 | Lat/Lon: 42.24, -71.17 | Population: 24711
--- 143. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 144. Randolph, MA (1)---
ZIP: 02368 | Lat/Lon: 42.17, -71.05 | Population: 32158
--- 145. Braintree, MA (1)---
ZIP: 02184 | Lat/Lon: 42.2, -71.0 | Population: 35744
--- 146. Quincy, MA (3)---
ZIP: 02169 | Lat/Lon: 42.26, -71.0 | Population: 55055
--- 147. Boston, MA (16)---
ZIP: 02115 | Lat/Lon: 42.34, -71.1 | Population: 28441
--- 148. Brockton, MA (2)---
ZIP: 02301 | Lat/Lon: 42.08, -71.02 | Population: 61025
--- 149. Quincy, MA (3)---
ZIP: 02169 | Lat/Lon: 42.26, -71.0 | Population: 55055
--- 150. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13 | Population: 21561
--- 151. Pembroke, MA (1)---
ZIP: 02359 | Lat/Lon: 42.06, -70.8 | Population: 17828
--- 152. Boston, MA (16)---
ZIP: 02115 | Lat/Lon: 42.34, -71.1 | Population: 28441
--- 153. Hyde Park, MA (1)---
ZIP: 02136 | Lat/Lon: 42.26, -71.13 | Population: 28488
--- 154. Brockton, MA (2)---
ZIP: 02301 | Lat/Lon: 42.08, -71.02 | Population: 61025
--- 155. Boston, MA (16)---
ZIP: 02115 | Lat/Lon: 42.34, -71.1 | Population: 28441
--- 156. Boston, MA (16)---
ZIP: 02115 | Lat/Lon: 42.34, -71.1 | Population: 28441
--- 157. Lowell, MA (4)---
ZIP: 01852 | Lat/Lon: 42.63, -71.3 | Population: 33508
--- 158. Salem, MA (1)---
ZIP: 01970 | Lat/Lon: 42.51, -70.9 | Population: 41109
--- 159. Andover, MA (1)---
ZIP: 01810 | Lat/Lon: 42.65, -71.14 | Population: 33201
--- 160. Lowell, MA (4)---
ZIP: 01852 | Lat/Lon: 42.63, -71.3 | Population: 33508
--- 161. Methuen, MA (1)---
ZIP: 01844 | Lat/Lon: 42.74, -71.18 | Population: 47249
--- 162. Andover, MA (1)---
ZIP: 01810 | Lat/Lon: 42.65, -71.14 | Population: 33201
--- 163. Haverhill, MA (3)---
ZIP: 01830 | Lat/Lon: 42.78, -71.08 | Population: 25137
--- 164. Revere, MA (1)---
ZIP: 02151 | Lat/Lon: 42.41, -70.99 | Population: 51808
--- 165. Haverhill, MA (3)---
ZIP: 01830 | Lat/Lon: 42.78, -71.08 | Population: 25137
--- 167. Salem, MA (1)---
ZIP: 01970 | Lat/Lon: 42.51, -70.9 | Population: 41109
--- 168. Acton, MA (2)---
ZIP: 01720 | Lat/Lon: 42.48, -71.46 | Population: 21361
--- 169. Malden, MA (1)---
ZIP: 02148 | Lat/Lon: 42.43, -71.05 | Population: 59503
--- 170. Melrose, MA (1)---
ZIP: 02176 | Lat/Lon: 42.45, -71.05 | Population: 26983
--- 171. Quincy, MA (3)---
ZIP: 02169 | Lat/Lon: 42.26, -71.0 | Population: 55055
--- 172. Brighton, MA (1)---
ZIP: 02135 | Lat/Lon: 42.35, -71.15 | Population: 42780
--- 173. Brookline, MA (2)---
ZIP: 02446 | Lat/Lon: 42.34, -71.12 | Population: 29311
--- 174. Boston, MA (16)---
ZIP: 02115 | Lat/Lon: 42.34, -71.1 | Population: 28441
--- 175. Sudbury, MA (1)---
ZIP: 01776 | Lat/Lon: 42.36, -71.4 | Population: 17659
--- 176. West Roxbury, MA (1)---
ZIP: 02132 | Lat/Lon: 42.28, -71.16 | Population: 25861
--- 177. Medford, MA (1)---
ZIP: 02155 | Lat/Lon: 42.42, -71.1 | Population: 57964
--- 178. Lynn, MA (4)---
ZIP: 01902 | Lat/Lon: 42.47, -70.94 | Population: 45139
--- 179. Revere, MA (1)---
ZIP: 02151 | Lat/Lon: 42.41, -70.99 | Population: 51808
--- 180. Andover, MA (1)---
ZIP: 01810 | Lat/Lon: 42.65, -71.14 | Population: 33201
--- 181. Wayland, MA (1)---
ZIP: 01778 | Lat/Lon: 42.36, -71.36 | Population: 13109
--- 182. Tyngsboro, MA (1)---
ZIP: 01879 | Lat/Lon: 42.68, -71.41 | Population: 11305
--- 183. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26 | Population: 30310
--- 184. Hampstead, NH (1)---
ZIP: 03841 | Lat/Lon: 42.87, -71.18 | Population: 6334
--- 185. Lowell, MA (4)---
ZIP: 01852 | Lat/Lon: 42.63, -71.3 | Population: 33508
--- 186. Lynn, MA (4)---
ZIP: 01902 | Lat/Lon: 42.47, -70.94 | Population: 45139
--- 188. Tewksbury, MA (1)---
ZIP: 01876 | Lat/Lon: 42.61, -71.23 | Population: 28667
--- 189. Salisbury, MA (1)---
ZIP: 01952 | Lat/Lon: 42.83, -70.84 | Population: 8283
--- 190. Groveland, MA (1)---
ZIP: 01834 | Lat/Lon: 42.75, -71.03 | Population: 6459
--- 191. Methuen, MA (1)---
ZIP: 01844 | Lat/Lon: 42.74, -71.18 | Population: 47249
--- 192. Salem, MA (1)---
ZIP: 01970 | Lat/Lon: 42.51, -70.9 | Population: 41109
--- 193. Haverhill, MA (3)---
ZIP: 01830 | Lat/Lon: 42.78, -71.08 | Population: 25137
--- 194. Milford, MA (1)---
ZIP: 01757 | Lat/Lon: 42.14, -71.51 | Population: 28061
--- 195. Holliston, MA (1)---
ZIP: 01746 | Lat/Lon: 42.2, -71.43 | Population: 13547
--- 196. Medway, MA (1)---
ZIP: 02053 | Lat/Lon: 42.16, -71.43 | Population: 12752
--- 197. Natick, MA (1)---
ZIP: 01760 | Lat/Lon: 42.28, -71.35 | Population: 32786
--- 198. Lynn, MA (4)---
ZIP: 01902 | Lat/Lon: 42.47, -70.94 | Population: 45139
--- 199. Milton, MA (1)---
ZIP: 02186 | Lat/Lon: 42.24, -71.08 | Population: 27003
--- 200. Taunton, MA (1)---
ZIP: 02780 | Lat/Lon: 41.9, -71.09 | Population: 49036
--- 201. Taunton, MA (1)---
ZIP: 02780 | Lat/Lon: 41.9, -71.09 | Population: 49036
--- 202. Tewksbury, MA (1)---
ZIP: 01876 | Lat/Lon: 42.61, -71.23 | Population: 28667
--- 203. Lynn, MA (4)---
ZIP: 01902 | Lat/Lon: 42.47, -70.94 | Population: 45139
--- 204. Amherst, MA (2)---
ZIP: 01002 | Lat/Lon: 42.37, -72.52 | Population: 29049
--- 205. Reading, MA (1)---
ZIP: 01867 | Lat/Lon: 42.53, -71.1 | Population: 23956
--- 206. Stow, MA (1)---
ZIP: 01775 | Lat/Lon: 42.43, -71.5 | Population: 6590
--- 207. Boston, MA (16)---
ZIP: 02115 | Lat/Lon: 42.34, -71.1 | Population: 28441
--- 208. Easthampton, MA (1)---
ZIP: 01027 | Lat/Lon: 42.26, -72.68 | Population: 17660
--- 209. Peabody, MA (1)---
ZIP: 01960 | Lat/Lon: 42.53, -70.97 | Population: 50944
--- 210. Norton, MA (1)---
ZIP: 02766 | Lat/Lon: 41.96, -71.18 | Population: 19031
--- 211. Raynham, MA (1)---
ZIP: 02767 | Lat/Lon: 41.93, -71.04 | Population: 13566
--- 212. Taunton, MA (1)---
ZIP: 02780 | Lat/Lon: 41.9, -71.09 | Population: 49036
--- 213. Taunton, MA (1)---
ZIP: 02780 | Lat/Lon: 41.9, -71.09 | Population: 49036
--- 214. Lynn, MA (4)---
ZIP: 01902 | Lat/Lon: 42.47, -70.94 | Population: 45139
--- 215. Norwood, MA (1)---
ZIP: 02062 | Lat/Lon: 42.18, -71.19 | Population: 28602
--- 216. Somerset, MA (2)---
ZIP: 02726 | Lat/Lon: 41.73, -71.15 | Population: 15534
--- 217. Brockton, MA (2)---
ZIP: 02301 | Lat/Lon: 42.08, -71.02 | Population: 61025
--- 218. Bridgewater, MA (1)---
ZIP: 02324 | Lat/Lon: 41.98, -70.97 | Population: 26563
--- 219. Brockton, MA (2)---
ZIP: 02301 | Lat/Lon: 42.08, -71.02 | Population: 61025
--- 220. Boston, MA (16)---
ZIP: 02115 | Lat/Lon: 42.34, -71.1 | Population: 28441
--- 221. Tyngsboro, MA (1)---
ZIP: 01879 | Lat/Lon: 42.68, -71.41 | Population: 11305
--- 222. Lynn, MA (4)---
ZIP: 01902 | Lat/Lon: 42.47, -70.94 | Population: 45139
--- 223. Haverhill, MA (3)---
ZIP: 01830 | Lat/Lon: 42.78, -71.08 | Population: 25137
--- 224. Wilmington, MA (1)---
ZIP: 01887 | Lat/Lon: 42.55, -71.16 | Population: 22325
--- 225. Boxford, MA (1)---
ZIP: 01921 | Lat/Lon: 42.67, -70.98 | Population: 7961
--- 226. Stoneham, MA (1)---
ZIP: 02180 | Lat/Lon: 42.47, -71.09 | Population: 21437
--- 227. Arlington, MA (2)---
ZIP: 02474 | Lat/Lon: 42.42, -71.16 | Population: 26312
--- 228. Kensington, NH (1)---
ZIP: 03442 | Lat/Lon: 43.0, -71.93 | Population: 1491
--- 229. Tewksbury, MA (1)---
ZIP: 01876 | Lat/Lon: 42.61, -71.23 | Population: 28667
--- 230. Townsend, MA (1)---
ZIP: 01469 | Lat/Lon: 42.66, -71.7 | Population: 6801
--- 231. Byfield, MA (1)---
ZIP: 01922 | Lat/Lon: 42.75, -70.93 | Population: 3108
--- 232. Beverly, MA (1)---
ZIP: 01915 | Lat/Lon: 42.57, -70.87 | Population: 39502
--- 233. Boston, MA (16)---
ZIP: 02115 | Lat/Lon: 42.34, -71.1 | Population: 28441
--- 234. Plaistow, NH (1)---
ZIP: 03865 | Lat/Lon: 42.83, -71.09 | Population: 7609
--- 235. Lawrence, MA (3)---
ZIP: 01841 | Lat/Lon: 42.71, -71.16 | Population: 47225
--- 236. Lawrence, MA (3)---
ZIP: 01841 | Lat/Lon: 42.71, -71.16 | Population: 47225
--- 237. Georgetown, MA (1)---
ZIP: 01833 | Lat/Lon: 42.73, -70.98 | Population: 8183
--- 238. Lawrence, MA (3)---
ZIP: 01841 | Lat/Lon: 42.71, -71.16 | Population: 47225
--- 239. Middleton, MA (1)---
ZIP: 01949 | Lat/Lon: 42.6, -71.01 | Population: 8987
--- 240. Lynn, MA (4)---
ZIP: 01902 | Lat/Lon: 42.47, -70.94 | Population: 45139
--- 241. Amesbury, MA (1)---
ZIP: 01913 | Lat/Lon: 42.85, -70.92 | Population: 16283
--- 242. Newburyport, MA (1)---
ZIP: 01950 | Lat/Lon: 42.81, -70.88 | Population: 17416
--- 243. Haverhill, MA (3)---
ZIP: 01830 | Lat/Lon: 42.78, -71.08 | Population: 25137
--- 244. Salisbury, MA (1)---

In [ ]:
df['current_lat'] = current_lat
df['current_lon'] = current_lon
df['current_town_population'] = current_town_population

In [ ]:
df.head(10)

,id_number,submission_date,age,disability,chapa_races,hispanic_latino,census_races,current_residence_town_city,current_residence_state,current_residence_zip,...,matched_address,fthb_class,msa,property_restriction,property_lat,property_lon,property_town_population,current_lat,current_lon,current_town_population
0,150733,2022-02-08,65,0,White/Non-Minority,0.0,White alone,Somerville,MA,02145,...,"8 CIDERPRESS WAY, NORTH ANDOVER, MA, 01845",0,"Boston-Cambridge-Newton, MA-NH",NaN,42.70,-71.11,28352,42.39,-71.10,25439
1,439181,2022-02-08,59,0,Hispanic/Latino,1.0,Unknown,Westford,MA,01886,...,"8 CIDERPRESS WAY, NORTH ANDOVER, MA, 01845",0,"Boston-Cambridge-Newton, MA-NH",NaN,42.70,-71.11,28352,42.58,-71.43,21951
2,697399,2022-02-08,0,0,Black or African American,0.0,Black or African American alone,Malden,MA,02148,...,"8 CIDERPRESS WAY, NORTH ANDOVER, MA, 01845",0,"Boston-Cambridge-Newton, MA-NH",NaN,42.70,-71.11,28352,42.43,-71.05,59503
3,191565,2022-02-08,0,0,White/Non-Minority,0.0,White alone,Haverhill,MA,01830,...,"8 CIDERPRESS WAY, NORTH ANDOVER, MA, 01845",0,"Boston-Cambridge-Newton, MA-NH",NaN,42.70,-71.11,28352,42.78,-71.08,25137
4,226436,2022-02-08,60,0,White/Non-Minority,0.0,White alone,Nashua,NH,03060,...,"8 CIDERPRESS WAY, NORTH ANDOVER, MA, 01845",0,"Boston-Cambridge-Newton, MA-NH",NaN,42.70,-71.11,28352,42.74,-71.46,29357
5,932459,2022-02-08,0,0,White/Non-Minority,0.0,White alone,East Boston,MA,02128,...,"8 CIDERPRESS WAY, NORTH ANDOVER, MA, 01845",0,"Boston-Cambridge-Newton, MA-NH",NaN,42.70,-71.11,28352,42.36,-71.01,40508
6,170029,2021-06-15,35,0,White/Non-Minority,0.0,White alone,Waltham,MA,02453,...,"1301 ALBION RD, BEDFORD, MA, 01730",0,"Boston-Cambridge-Newton, MA-NH",NaN,42.48,-71.26,13221,42.37,-71.24,28968
7,725305,2021-06-15,0,0,White/Non-Minority,0.0,White alone,Woburn,MA,01801,...,"1301 ALBION RD, BEDFORD, MA, 01730",0,"Boston-Cambridge-Newton, MA-NH",NaN,42.48,-71.26,13221,42.48,-71.15,38903
8,569863,2021-06-15,38,0,Black or African American,0.0,Black or African American alone,Woburn,MA,01801,...,"1301 ALBION RD, BEDFORD, MA, 01730",0,"Boston-Cambridge-Newton, MA-NH",NaN,42.48,-71.26,13221,42.48,-71.15,38903
9,746052,2021-06-15,63,0,Asian/Pacific Islander,0.0,Asian alone,Burlington,MA,01803,...,"1301 ALBION RD, BEDFORD, MA, 01730",0,"Boston-Cambridge-Newton, MA-NH",NaN,42.48,-71.26,13221,42.50,-71.20,24487

In [ ]:
df.to_csv("/content/drive/MyDrive/Colab Notebooks/total_zip_crawling.csv", index=False)