# Geo info for Chapter 40B Applicant data 2021-25

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [ ]:
!pip install sqlalchemy_mate==2.0.0.0

Requirement already satisfied: sqlalchemy_mate==2.0.0.0 in /usr/local/lib/python3.12/dist-packages (2.0.0.0)
Requirement already satisfied: sqlalchemy<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy_mate==2.0.0.0) (2.0.44)
Requirement already satisfied: prettytable<4.0.0,>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy_mate==2.0.0.0) (3.16.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable<4.0.0,>=3.0.0->sqlalchemy_mate==2.0.0.0) (0.2.14)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3.0.0,>=2.0.0->sqlalchemy_mate==2.0.0.0) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3.0.0,>=2.0.0->sqlalchemy_mate==2.0.0.0) (4.15.0)

In [ ]:
!pip install uszipcode

Requirement already satisfied: uszipcode in /usr/local/lib/python3.12/dist-packages (1.0.1)
Requirement already satisfied: attrs in /usr/local/lib/python3.12/dist-packages (from uszipcode) (25.4.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from uszipcode) (2.32.4)
Requirement already satisfied: pathlib-mate in /usr/local/lib/python3.12/dist-packages (from uszipcode) (1.3.2)
Requirement already satisfied: atomicwrites in /usr/local/lib/python3.12/dist-packages (from uszipcode) (1.4.1)
Requirement already satisfied: fuzzywuzzy in /usr/local/lib/python3.12/dist-packages (from uszipcode) (0.18.0)
Requirement already satisfied: haversine>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from uszipcode) (2.9.0)
Requirement already satisfied: SQLAlchemy>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from uszipcode) (2.0.44)
Requirement already satisfied: sqlalchemy-mate>=1.4.28.3 in /usr/local/lib/python3.12/dist-packages (from uszipcode) (2.0.0.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy>=1.4.0->uszipcode) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy>=1.4.0->uszipcode) (4.15.0)
Requirement already satisfied: prettytable<4.0.0,>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy-mate>=1.4.28.3->uszipcode) (3.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->uszipcode) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->uszipcode) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->uszipcode) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->uszipcode) (2025.10.5)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable<4.0.0,>=3.0.0->sqlalchemy-mate>=1.4.28.3->uszipcode) (0.2.14)

In [ ]:
from uszipcode import SearchEngine
search = SearchEngine()

## Load dataset

In [ ]:
file_path = "/content/drive/MyDrive/Colab Notebooks/CHAPA_Chapter-40B_Application-Data_2021-2025_merged_v0.3.csv"
df = pd.read_csv(file_path)
df.columns = df.columns.str.strip().str.lower()
df.head()

,id_number,submission_date,age,disability,chapa_races,census_races,current_residence_town_city,current_residence_state,current_residence_zip,application_source,...,race_cleaned,race_type,race_american_indian_or_alaska_native,race_asian,race_black_or_african_american,race_hispanic_or_latino,race_middle_eastern_or_north_african,race_native_hawaiian_or_pacific_islander,race_other__prefer_not_to_answer,race_white
0,150733,2022-02-08,65,0,White/Non-Minority,White alone,Somerville,MA,NaN,Unknown,...,['White'],Single Race,0,0,0,0,0,0,0,1
1,439181,2022-02-08,59,0,Hispanic/Latino,Unknown,Westford,MA,NaN,Unknown,...,['Hispanic or Latino'],Single Race,0,0,0,1,0,0,0,0
2,697399,2022-02-08,0,0,Black or African American,Black or African American alone,Malden,MA,NaN,Unknown,...,['Black or African American'],Single Race,0,0,1,0,0,0,0,0
3,191565,2022-02-08,0,0,White/Non-Minority,White alone,Haverhill,MA,NaN,Unknown,...,['White'],Single Race,0,0,0,0,0,0,0,1
4,226436,2022-02-08,60,0,White/Non-Minority,White alone,Nashua,NH,NaN,Unknown,...,['White'],Single Race,0,0,0,0,0,0,0,1

## Filter certain matched addresses to pull geo info

* Select 'Exact', 'Non_Exact', 'Zillow' rows
* Drop 'Unknown' in current residence

In [ ]:
df = df[
    (df['match_type'].isin(['Exact', 'Non_Exact', 'Zillow'])) &
    (df['current_residence_town_city'] != 'Unknown') &
    (df['current_residence_state'] != 'Unknown') &
    (df['age'] != 0)
].reset_index(drop=True)
len(df)

1465

In [ ]:
# property_zip: extract from matched_address

def extract_zip(addy):
    if pd.isna(addy):
        return None
    match = re.search(r",[^,]*?(\d{5})\s*$", addy)  # look after the last comma and extract 5 digits
    if match:
        return match.group(1)
    return None

df.loc[df["property_zip"].isna(), "property_zip"] = df.loc[df["property_zip"].isna(), "matched_address"].apply(extract_zip)

/tmp/ipython-input-1565990801.py:11: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['01845' '01845' '01845' ... '02465' '01772' '01453']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df["property_zip"].isna(), "property_zip"] = df.loc[df["property_zip"].isna(), "matched_address"].apply(extract_zip)

# Get Longitude, Latitude from uszipecode using property_zip

In [ ]:
# property_long, property_lat
property_lat = [0 for i in range(len(df))]
property_lon = [0 for i in range(len(df))]

town_missing = []

for i in range(len(df)):

  zip_code = df['property_zip'][i]

  results = search.by_zipcode(zip_code)

  if results:

    latitude = results.lat
    longitude = results.lng

    property_lat[i] = latitude
    property_lon[i] = longitude

    print(f"--- {i}, {zip_code}, {latitude}, {longitude} ---")

  else:
    print(f"'{i}, {latitude}, {longitude}' could not be find")
    town_missing.append(i)

print(town_missing)

df['property_lat'] = property_lat
df['property_lon'] = property_lon

--- 0, 01845, 42.7, -71.11 ---
--- 1, 01845, 42.7, -71.11 ---
--- 2, 01845, 42.7, -71.11 ---
--- 3, 01730, 42.48, -71.26 ---
--- 4, 01730, 42.48, -71.26 ---
--- 5, 01730, 42.48, -71.26 ---
--- 6, 01730, 42.48, -71.26 ---
--- 7, 02718, 41.87, -71.01 ---
--- 8, 01862, 42.58, -71.3 ---
--- 9, 01862, 42.58, -71.3 ---
--- 10, 01862, 42.58, -71.3 ---
--- 11, 01862, 42.58, -71.3 ---
--- 12, 01862, 42.58, -71.3 ---
--- 13, 01862, 42.58, -71.3 ---
--- 14, 01862, 42.58, -71.3 ---
--- 15, 01862, 42.58, -71.3 ---
--- 16, 01862, 42.58, -71.3 ---
--- 17, 01862, 42.58, -71.3 ---
--- 18, 01862, 42.58, -71.3 ---
--- 19, 01862, 42.58, -71.3 ---
--- 20, 01938, 42.67, -70.83 ---
--- 21, 01938, 42.67, -70.83 ---
--- 22, 01845, 42.7, -71.11 ---
--- 23, 01845, 42.7, -71.11 ---
--- 24, 01845, 42.7, -71.11 ---
--- 25, 01845, 42.7, -71.11 ---
--- 26, 01845, 42.7, -71.11 ---
--- 27, 01845, 42.7, -71.11 ---
--- 28, 01845, 42.7, -71.11 ---
--- 29, 01845, 42.7, -71.11 ---
--- 30, 01845, 42.7, -71.11 ---
--- 31, 01845, 42.7, -71.11 ---
--- 32, 01845, 42.7, -71.11 ---
--- 33, 01845, 42.7, -71.11 ---
--- 34, 01845, 42.7, -71.11 ---
--- 35, 01845, 42.7, -71.11 ---
--- 36, 01845, 42.7, -71.11 ---
--- 37, 01845, 42.7, -71.11 ---
--- 38, 02053, 42.16, -71.43 ---
--- 39, 02053, 42.16, -71.43 ---
--- 40, 02053, 42.16, -71.43 ---
--- 41, 02053, 42.16, -71.43 ---
--- 42, 02053, 42.16, -71.43 ---
--- 43, 02053, 42.16, -71.43 ---
--- 44, 02053, 42.16, -71.43 ---
--- 45, 02053, 42.16, -71.43 ---
--- 46, 02053, 42.16, -71.43 ---
--- 47, 01860, 42.83, -71.0 ---
--- 48, 01862, 42.58, -71.3 ---
--- 49, 01862, 42.58, -71.3 ---
--- 50, 01862, 42.58, -71.3 ---
--- 51, 02184, 42.2, -71.0 ---
--- 52, 02184, 42.2, -71.0 ---
--- 53, 01845, 42.7, -71.11 ---
--- 54, 01845, 42.7, -71.11 ---
--- 55, 02021, 42.15, -71.13 ---
--- 56, 02021, 42.15, -71.13 ---
--- 57, 02021, 42.15, -71.13 ---
--- 58, 02021, 42.15, -71.13 ---
--- 59, 02021, 42.15, -71.13 ---
--- 60, 02021, 42.15, -71.13 ---
--- 61, 02021, 42.15, -71.13 ---
--- 62, 01845, 42.7, -71.11 ---
--- 63, 01845, 42.7, -71.11 ---
--- 64, 01845, 42.7, -71.11 ---
--- 65, 01845, 42.7, -71.11 ---
--- 66, 01518, 42.12, -72.11 ---
--- 67, 01982, 42.62, -70.86 ---
--- 68, 01982, 42.62, -70.86 ---
--- 69, 01982, 42.62, -70.86 ---
--- 70, 01982, 42.62, -70.86 ---
--- 71, 01982, 42.62, -70.86 ---
--- 72, 01982, 42.62, -70.86 ---
--- 73, 01845, 42.7, -71.11 ---
--- 74, 01845, 42.7, -71.11 ---
--- 75, 01845, 42.7, -71.11 ---
--- 76, 01845, 42.7, -71.11 ---
--- 77, 01945, 42.5, -70.85 ---
--- 78, 01945, 42.5, -70.85 ---
--- 79, 01945, 42.5, -70.85 ---
--- 80, 01945, 42.5, -70.85 ---
--- 81, 01945, 42.5, -70.85 ---
--- 82, 01844, 42.74, -71.18 ---
--- 83, 01844, 42.74, -71.18 ---
--- 84, 01844, 42.74, -71.18 ---
--- 85, 01821, 42.55, -71.26 ---
--- 86, 01821, 42.55, -71.26 ---
--- 87, 01821, 42.55, -71.26 ---
--- 88, 01821, 42.55, -71.26 ---
--- 89, 01821, 42.55, -71.26 ---
--- 90, 01821, 42.55, -71.26 ---
--- 91, 01821, 42.55, -71.26 ---
--- 92, 02021, 42.15, -71.13 ---
--- 93, 02021, 42.15, -71.13 ---
--- 94, 02021, 42.15, -71.13 ---
--- 95, 02021, 42.15, -71.13 ---
--- 96, 02021, 42.15, -71.13 ---
--- 97, 02021, 42.15, -71.13 ---
--- 98, 02021, 42.15, -71.13 ---
--- 99, 02021, 42.15, -71.13 ---
--- 100, 02021, 42.15, -71.13 ---
--- 101, 02021, 42.15, -71.13 ---
--- 102, 02021, 42.15, -71.13 ---
--- 103, 02021, 42.15, -71.13 ---
--- 104, 02021, 42.15, -71.13 ---
--- 105, 02021, 42.15, -71.13 ---
--- 106, 02021, 42.15, -71.13 ---
--- 107, 02021, 42.15, -71.13 ---
--- 108, 02021, 42.15, -71.13 ---
--- 109, 02021, 42.15, -71.13 ---
--- 110, 02021, 42.15, -71.13 ---
--- 111, 02021, 42.15, -71.13 ---
--- 112, 02021, 42.15, -71.13 ---
--- 113, 01845, 42.7, -71.11 ---
--- 114, 01845, 42.7, -71.11 ---
--- 115, 01845, 42.7, -71.11 ---
--- 116, 01845, 42.7, -71.11 ---
--- 117, 01845, 42.7, -71.11 ---
--- 118, 01845, 42.7, -71.11 ---
--- 119, 01845, 42.7, -71.11 ---
--- 120, 01845, 42.7, -71.11 ---
--- 121, 01845, 42.7, -71.11 ---
--- 122, 01845, 42.7, -71.11 ---
--- 123, 01845, 42.7, -71.11 ---
--- 124, 01864, 42.58, -71.08 ---
--- 125, 01864, 42.58, -71.08 ---
--- 126, 01741, 42.53, -71.35 ---
--- 127, 01741, 42.53, -71.35 ---
--- 128, 01741, 42.53, -71.35 ---
--- 129, 01741, 42.53, -71.35 ---
--- 130, 01741, 42.53, -71.35 ---
--- 131, 01741, 42.53, -71.35 ---
--- 132, 01741, 42.53, -71.35 ---
--- 133, 01741, 42.53, -71.35 ---
--- 134, 01741, 42.53, -71.35 ---
--- 135, 01451, 42.5, -71.58 ---
--- 136, 01451, 42.5, -71.58 ---
--- 137, 01451, 42.5, -71.58 ---
--- 138, 01844, 42.74, -71.18 ---
--- 139, 01844, 42.74, -71.18 ---
--- 140, 01027, 42.26, -72.68 ---
--- 141, 02766, 41.96, -71.18 ---
--- 142, 01432, 42.56, -71.58 ---
--- 143, 01432, 42.56, -71.58 ---
--- 144, 01432, 42.56, -71.58 ---
--- 145, 01845, 42.7, -71.11 ---
--- 146, 01845, 42.7, -71.11 ---
--- 147, 01845, 42.7, -71.11 ---
--- 148, 01845, 42.7, -71.11 ---
--- 149, 01845, 42.7, -71.11 ---
--- 150, 01845, 42.7, -71.11 ---
--- 151, 01845, 42.7, -71.11 ---
--- 152, 01845, 42.7, -71.11 ---
--- 153, 01845, 42.7, -71.11 ---
--- 154, 01845, 42.7, -71.11 ---
--- 155, 01845, 42.7, -71.11 ---
--- 156, 01845, 42.7, -71.11 ---
--- 157, 01845, 42.7, -71.11 ---
--- 158, 01845, 42.7, -71.11 ---
--- 159, 01950, 42.81, -70.88 ---
--- 160, 01950, 42.81, -70.88 ---
--- 161, 01950, 42.81, -70.88 ---
--- 162, 01950, 42.81, -70.88 ---
--- 163, 01950, 42.81, -70.88 ---
--- 164, 01880, 42.5, -71.06 ---
--- 165, 01880, 42.5, -71.06 ---
--- 166, 01880, 42.5, -71.06 ---
--- 167, 01880, 42.5, -71.06 ---
--- 168, 01880, 42.5, -71.06 ---
--- 169, 01880, 42.5, -71.06 ---
--- 170, 01845, 42.7, -71.11 ---
--- 171, 01845, 42.7, -71.11 ---
--- 172, 01730, 42.48, -71.26 ---
--- 173, 01730, 42.48, -71.26 ---
--- 174, 01730, 42.48, -71.26 ---
--- 175, 01864, 42.58, -71.08 ---
--- 176, 02053, 42.16, -71.43 ---
--- 177, 02053, 42.16, -71.43 ---
--- 178, 02053, 42.16, -71.43 ---
--- 179, 02053, 42.16, -71.43 ---
--- 180, 02053, 42.16, -71.43 ---
--- 181, 02053, 42.16, -71.43 ---
--- 182, 02053, 42.16, -71.43 ---
--- 183, 02053, 42.16, -71.43 ---
--- 184, 02053, 42.16, -71.43 ---
--- 185, 02053, 42.16, -71.43 ---
--- 186, 02053, 42.16, -71.43 ---
--- 187, 02053, 42.16, -71.43 ---
--- 188, 02053, 42.16, -71.43 ---
--- 189, 02053, 42.16, -71.43 ---
--- 190, 02053, 42.16, -71.43 ---
--- 191, 02053, 42.16, -71.43 ---
--- 192, 02053, 42.16, -71.43 ---
--- 193, 02053, 42.16, -71.43 ---
--- 194, 02053, 42.16, -71.43 ---
--- 195, 02053, 42.16, -71.43 ---
--- 196, 02053, 42.16, -71.43 ---
--- 197, 02053, 42.16, -71.43 ---
--- 198, 02053, 42.16, -71.43 ---
--- 199, 02053, 42.16, -71.43 ---
--- 200, 02053, 42.16, -71.43 ---
--- 201, 02053, 42.16, -71.43 ---
--- 202, 02053, 42.16, -71.43 ---
--- 203, 02053, 42.16, -71.43 ---
--- 204, 02053, 42.16, -71.43 ---
--- 205, 02053, 42.16, -71.43 ---
--- 206, 02053, 42.16, -71.43 ---
--- 207, 02053, 42.16, -71.43 ---
--- 208, 02053, 42.16, -71.43 ---
--- 209, 02053, 42.16, -71.43 ---
--- 210, 02053, 42.16, -71.43 ---
--- 211, 02053, 42.16, -71.43 ---
--- 212, 02053, 42.16, -71.43 ---
--- 213, 02053, 42.16, -71.43 ---
--- 214, 02053, 42.16, -71.43 ---
--- 215, 02053, 42.16, -71.43 ---
--- 216, 02053, 42.16, -71.43 ---
--- 217, 02053, 42.16, -71.43 ---
--- 218, 02053, 42.16, -71.43 ---
--- 219, 02053, 42.16, -71.43 ---
--- 220, 02053, 42.16, -71.43 ---
--- 221, 02053, 42.16, -71.43 ---
--- 222, 02053, 42.16, -71.43 ---
--- 223, 02053, 42.16, -71.43 ---
--- 224, 02053, 42.16, -71.43 ---
--- 225, 02053, 42.16, -71.43 ---
--- 226, 02053, 42.16, -71.43 ---
--- 227, 02053, 42.16, -71.43 ---
--- 228, 02053, 42.16, -71.43 ---
--- 229, 02053, 42.16, -71.43 ---
--- 230, 02053, 42.16, -71.43 ---
--- 231, 02053, 42.16, -71.43 ---
--- 232, 02053, 42.16, -71.43 ---
--- 233, 02053, 42.16, -71.43 ---
--- 234, 02053, 42.16, -71.43 ---
--- 235, 02053, 42.16, -71.43 ---
--- 236, 02053, 42.16, -71.43 ---
--- 237, 02053, 42.16, -71.43 ---
--- 238, 02053, 42.16, -71.43 ---
--- 239, 02053, 42.16, -71.43 ---
--- 240, 02053, 42.16, -71.43 ---
--- 241, 02053, 42.16, -71.43 ---
--- 242, 01560, 42.17, -71.68 ---
--- 243, 01560, 42.17, -71.68 ---
--- 244, 01560, 42.17, -71.68 ---
--- 245, 02370, 42.13, -70.91 ---
--- 246, 02370, 42.13, -70.91 ---
--- 247, 02370, 42.13, -70.91 ---
--- 248, 02370, 42.13, -70.91 ---
--- 249, 02370, 42.13, -70.91 ---
--- 250, 02370, 42.13, -70.91 ---
--- 251, 02370, 42.13, -70.91 ---
--- 252, 02370, 42.13, -70.91 ---
--- 253, 02370, 42.13, -70.91 ---
--- 254, 02370, 42.13, -70.91 ---
--- 255, 02370, 42.13, -70.91 ---
--- 256, 02370, 42.13, -70.91 ---
--- 257, 02370, 42.13, -70.91 ---
--- 258, 02370, 42.13, -70.91 ---
--- 259, 01453, 42.51, -71.77 ---
--- 260, 01880, 42.5, -71.06 ---
--- 261, 02021, 42.15, -71.13 ---
--- 262, 01756, 42.1, -71.55 ---
--- 263, 01950, 42.81, -70.88 ---
--- 264, 01583, 42.36, -71.78 ---
--- 265, 02539, 41.38, -70.53 ---
--- 266, 01864, 42.58, -71.08 ---
--- 267, 01564, 42.43, -71.75 ---
--- 268, 01845, 42.7, -71.11 ---
--- 269, 02571, 41.76, -70.71 ---
--- 270, 01845, 42.7, -71.11 ---
--- 271, 01560, 42.17, -71.68 ---
--- 272, 02043, 42.23, -70.88 ---
--- 273, 01772, 42.3, -71.51 ---
--- 274, 01756, 42.1, -71.55 ---
--- 275, 01880, 42.5, -71.06 ---
--- 276, 01756, 42.1, -71.55 ---
--- 277, 02184, 42.2, -71.0 ---
--- 278, 02184, 42.2, -71.0 ---
--- 279, 02184, 42.2, -71.0 ---
--- 280, 02324, 41.98, -70.97 ---
--- 281, 02021, 42.15, -71.13 ---
--- 282, 02465, 42.35, -71.22 ---
--- 283, 01432, 42.56, -71.58 ---
--- 284, 01772, 42.3, -71.51 ---
--- 285, 02571, 41.76, -70.71 ---
--- 286, 02571, 41.76, -70.71 ---
--- 287, 01772, 42.3, -71.51 ---
--- 288, 01469, 42.66, -71.7 ---
--- 289, 01432, 42.56, -71.58 ---
--- 290, 02043, 42.23, -70.88 ---
--- 291, 01560, 42.17, -71.68 ---
--- 292, 01560, 42.17, -71.68 ---
--- 293, 01772, 42.3, -71.51 ---
--- 294, 01756, 42.1, -71.55 ---
--- 295, 01583, 42.36, -71.78 ---
--- 296, 01860, 42.83, -71.0 ---
--- 297, 02043, 42.23, -70.88 ---
--- 298, 01844, 42.74, -71.18 ---
--- 299, 01560, 42.17, -71.68 ---
--- 300, 01757, 42.14, -71.51 ---
--- 301, 01756, 42.1, -71.55 ---
--- 302, 01564, 42.43, -71.75 ---
--- 303, 02465, 42.35, -71.22 ---
--- 304, 02043, 42.23, -70.88 ---
--- 305, 02382, 42.08, -70.93 ---
--- 306, 02021, 42.15, -71.13 ---
--- 307, 01432, 42.56, -71.58 ---
--- 308, 02021, 42.15, -71.13 ---
--- 309, 02184, 42.2, -71.0 ---
--- 310, 02465, 42.35, -71.22 ---
--- 311, 01756, 42.1, -71.55 ---
--- 312, 01564, 42.43, -71.75 ---
--- 313, 02465, 42.35, -71.22 ---
--- 314, 02021, 42.15, -71.13 ---
--- 315, 02539, 41.38, -70.53 ---
--- 316, 01560, 42.17, -71.68 ---
--- 317, 01772, 42.3, -71.51 ---
--- 318, 02465, 42.35, -71.22 ---
--- 319, 02539, 41.38, -70.53 ---
--- 320, 01453, 42.51, -71.77 ---
--- 321, 02571, 41.76, -70.71 ---
--- 322, 02324, 41.98, -70.97 ---
--- 323, 01844, 42.74, -71.18 ---
--- 324, 02539, 41.38, -70.53 ---
--- 325, 01880, 42.5, -71.06 ---
--- 326, 01583, 42.36, -71.78 ---
--- 327, 01432, 42.56, -71.58 ---
--- 328, 01756, 42.1, -71.55 ---
--- 329, 01772, 42.3, -71.51 ---
--- 330, 01453, 42.51, -71.77 ---
--- 331, 01560, 42.17, -71.68 ---
--- 332, 01757, 42.14, -71.51 ---
--- 333, 01532, 42.31, -71.64 ---
--- 334, 01880, 42.5, -71.06 ---
--- 335, 01453, 42.51, -71.77 ---
--- 336, 02539, 41.38, -70.53 ---
--- 337, 02324, 41.98, -70.97 ---
--- 338, 01532, 42.31, -71.64 ---
--- 339, 01583, 42.36, -71.78 ---
--- 340, 01583, 42.36, -71.78 ---
--- 341, 01772, 42.3, -71.51 ---
--- 342, 01564, 42.43, -71.75 ---
--- 343, 02539, 41.38, -70.53 ---
--- 344, 02184, 42.2, -71.0 ---
--- 345, 02184, 42.2, -71.0 ---
--- 346, 01450, 42.6, -71.57 ---
--- 347, 02766, 41.96, -71.18 ---
--- 348, 02718, 41.87, -71.01 ---
--- 349, 01432, 42.56, -71.58 ---
--- 350, 02184, 42.2, -71.0 ---
--- 351, 02184, 42.2, -71.0 ---
--- 352, 01583, 42.36, -71.78 ---
--- 353, 01583, 42.36, -71.78 ---
--- 354, 02021, 42.15, -71.13 ---
--- 355, 02021, 42.15, -71.13 ---
--- 356, 01772, 42.3, -71.51 ---
--- 357, 01453, 42.51, -71.77 ---
--- 358, 01453, 42.51, -71.77 ---
--- 359, 01560, 42.17, -71.68 ---
--- 360, 02021, 42.15, -71.13 ---
--- 361, 01950, 42.81, -70.88 ---
--- 362, 01880, 42.5, -71.06 ---
--- 363, 01845, 42.7, -71.11 ---
--- 364, 01583, 42.36, -71.78 ---
--- 365, 01772, 42.3, -71.51 ---
--- 366, 01564, 42.43, -71.75 ---
--- 367, 01564, 42.43, -71.75 ---
--- 368, 01453, 42.51, -71.77 ---
--- 369, 01450, 42.6, -71.57 ---
--- 370, 01453, 42.51, -71.77 ---
--- 371, 01532, 42.31, -71.64 ---
--- 372, 01560, 42.17, -71.68 ---
--- 373, 01880, 42.5, -71.06 ---
--- 374, 01450, 42.6, -71.57 ---
--- 375, 02043, 42.23, -70.88 ---
--- 376, 01772, 42.3, -71.51 ---
--- 377, 01864, 42.58, -71.08 ---
--- 378, 01583, 42.36, -71.78 ---
--- 379, 02184, 42.2, -71.0 ---
--- 380, 02184, 42.2, -71.0 ---
--- 381, 02184, 42.2, -71.0 ---
--- 382, 01583, 42.36, -71.78 ---
--- 383, 02766, 41.96, -71.18 ---
--- 384, 01772, 42.3, -71.51 ---
--- 385, 01432, 42.56, -71.58 ---
--- 386, 01453, 42.51, -71.77 ---
--- 387, 01453, 42.51, -71.77 ---
--- 388, 01950, 42.81, -70.88 ---
--- 389, 01950, 42.81, -70.88 ---
--- 390, 01027, 42.26, -72.68 ---
--- 391, 01810, 42.65, -71.14 ---
--- 392, 01469, 42.66, -71.7 ---
--- 393, 01560, 42.17, -71.68 ---
--- 394, 01880, 42.5, -71.06 ---
--- 395, 02571, 41.76, -70.71 ---
--- 396, 01950, 42.81, -70.88 ---
--- 397, 02766, 41.96, -71.18 ---
--- 398, 02571, 41.76, -70.71 ---
--- 399, 01730, 42.48, -71.26 ---
--- 400, 01844, 42.74, -71.18 ---
--- 401, 01757, 42.14, -71.51 ---
--- 402, 01772, 42.3, -71.51 ---
--- 403, 01730, 42.48, -71.26 ---
--- 404, 02465, 42.35, -71.22 ---
--- 405, 01757, 42.14, -71.51 ---
--- 406, 01560, 42.17, -71.68 ---
--- 407, 01757, 42.14, -71.51 ---
--- 408, 02184, 42.2, -71.0 ---
--- 409, 02184, 42.2, -71.0 ---
--- 410, 02347, 41.85, -70.95 ---
--- 411, 02382, 42.08, -70.93 ---
--- 412, 01583, 42.36, -71.78 ---
--- 413, 02718, 41.87, -71.01 ---
--- 414, 01756, 42.1, -71.55 ---
--- 415, 01560, 42.17, -71.68 ---
--- 416, 01532, 42.31, -71.64 ---
--- 417, 01560, 42.17, -71.68 ---
--- 418, 02465, 42.35, -71.22 ---
--- 419, 01756, 42.1, -71.55 ---
--- 420, 02766, 41.96, -71.18 ---
--- 421, 02379, 42.01, -71.0 ---
--- 422, 01772, 42.3, -71.51 ---
--- 423, 01756, 42.1, -71.55 ---
--- 424, 01532, 42.31, -71.64 ---
--- 425, 02021, 42.15, -71.13 ---
--- 426, 01845, 42.7, -71.11 ---
--- 427, 01468, 42.55, -72.06 ---
--- 428, 02021, 42.15, -71.13 ---
--- 429, 01756, 42.1, -71.55 ---
--- 430, 02043, 42.23, -70.88 ---
--- 431, 01583, 42.36, -71.78 ---
--- 432, 01886, 42.58, -71.43 ---
--- 433, 01844, 42.74, -71.18 ---
--- 434, 01845, 42.7, -71.11 ---
--- 435, 01453, 42.51, -71.77 ---
--- 436, 01564, 42.43, -71.75 ---
--- 437, 01027, 42.26, -72.68 ---
--- 438, 02184, 42.2, -71.0 ---
--- 439, 01772, 42.3, -71.51 ---
--- 440, 01950, 42.81, -70.88 ---
--- 441, 01583, 42.36, -71.78 ---
--- 442, 01583, 42.36, -71.78 ---
--- 443, 02537, 41.73, -70.43 ---
--- 444, 02537, 41.73, -70.43 ---
--- 445, 02537, 41.73, -70.43 ---
--- 446, 01756, 42.1, -71.55 ---
--- 447, 01864, 42.58, -71.08 ---
--- 448, 01583, 42.36, -71.78 ---
--- 449, 01756, 42.1, -71.55 ---
--- 450, 01880, 42.5, -71.06 ---
--- 451, 01560, 42.17, -71.68 ---
--- 452, 01532, 42.31, -71.64 ---
--- 453, 01453, 42.51, -71.77 ---
--- 454, 01432, 42.56, -71.58 ---
--- 455, 01564, 42.43, -71.75 ---
--- 456, 02324, 41.98, -70.97 ---
--- 457, 01880, 42.5, -71.06 ---
--- 458, 01564, 42.43, -71.75 ---
--- 459, 01564, 42.43, -71.75 ---
--- 460, 01772, 42.3, -71.51 ---
--- 461, 02465, 42.35, -71.22 ---
--- 462, 01945, 42.5, -70.85 ---
--- 463, 02043, 42.23, -70.88 ---
--- 464, 01756, 42.1, -71.55 ---
--- 465, 01432, 42.56, -71.58 ---
--- 466, 01453, 42.51, -71.77 ---
--- 467, 02324, 41.98, -70.97 ---
--- 468, 02382, 42.08, -70.93 ---
--- 469, 01938, 42.67, -70.83 ---
--- 470, 01945, 42.5, -70.85 ---
--- 471, 01950, 42.81, -70.88 ---
--- 472, 02184, 42.2, -71.0 ---
--- 473, 02184, 42.2, -71.0 ---
--- 474, 02766, 41.96, -71.18 ---
--- 475, 01938, 42.67, -70.83 ---
--- 476, 01864, 42.58, -71.08 ---
--- 477, 02043, 42.23, -70.88 ---
--- 478, 01845, 42.7, -71.11 ---
--- 479, 01583, 42.36, -71.78 ---
--- 480, 01453, 42.51, -71.77 ---
--- 481, 01756, 42.1, -71.55 ---
--- 482, 01564, 42.43, -71.75 ---
--- 483, 01560, 42.17, -71.68 ---
--- 484, 01757, 42.14, -71.51 ---
--- 485, 01532, 42.31, -71.64 ---
--- 486, 01560, 42.17, -71.68 ---
--- 487, 01864, 42.58, -71.08 ---
--- 488, 01756, 42.1, -71.55 ---
--- 489, 02324, 41.98, -70.97 ---
--- 490, 02043, 42.23, -70.88 ---
--- 491, 01950, 42.81, -70.88 ---
--- 492, 02021, 42.15, -71.13 ---
--- 493, 01756, 42.1, -71.55 ---
--- 494, 01756, 42.1, -71.55 ---
--- 495, 01886, 42.58, -71.43 ---
--- 496, 02184, 42.2, -71.0 ---
--- 497, 01469, 42.66, -71.7 ---
--- 498, 01453, 42.51, -71.77 ---
--- 499, 01532, 42.31, -71.64 ---
--- 500, 02324, 41.98, -70.97 ---
--- 501, 02021, 42.15, -71.13 ---
--- 502, 02184, 42.2, -71.0 ---
--- 503, 02184, 42.2, -71.0 ---
--- 504, 01027, 42.26, -72.68 ---
--- 505, 01772, 42.3, -71.51 ---
--- 506, 01749, 42.39, -71.56 ---
--- 507, 01749, 42.39, -71.56 ---
--- 508, 01749, 42.39, -71.56 ---
--- 509, 01749, 42.39, -71.56 ---
--- 510, 01450, 42.6, -71.57 ---
--- 511, 01450, 42.6, -71.57 ---
--- 512, 01564, 42.43, -71.75 ---
--- 513, 02766, 41.96, -71.18 ---
--- 514, 02766, 41.96, -71.18 ---
--- 515, 02766, 41.96, -71.18 ---
--- 516, 01583, 42.36, -71.78 ---
--- 517, 01844, 42.74, -71.18 ---
--- 518, 01845, 42.7, -71.11 ---
--- 519, 01560, 42.17, -71.68 ---
--- 520, 01532, 42.31, -71.64 ---
--- 521, 01560, 42.17, -71.68 ---
--- 522, 01756, 42.1, -71.55 ---
--- 523, 02766, 41.96, -71.18 ---
--- 524, 01027, 42.26, -72.68 ---
--- 525, 02379, 42.01, -71.0 ---
--- 526, 02382, 42.08, -70.93 ---
--- 527, 02718, 41.87, -71.01 ---
--- 528, 02379, 42.01, -71.0 ---
--- 529, 01772, 42.3, -71.51 ---
--- 530, 01432, 42.56, -71.58 ---
--- 531, 01432, 42.56, -71.58 ---
--- 532, 01432, 42.56, -71.58 ---
--- 533, 01432, 42.56, -71.58 ---
--- 534, 01845, 42.7, -71.11 ---
--- 535, 02043, 42.23, -70.88 ---
--- 536, 01886, 42.58, -71.43 ---
--- 537, 01757, 42.14, -71.51 ---
--- 538, 01560, 42.17, -71.68 ---
--- 539, 01532, 42.31, -71.64 ---
--- 540, 01749, 42.39, -71.56 ---
--- 541, 01749, 42.39, -71.56 ---
--- 542, 01583, 42.36, -71.78 ---
--- 543, 01432, 42.56, -71.58 ---
--- 544, 01757, 42.14, -71.51 ---
--- 545, 01560, 42.17, -71.68 ---
--- 546, 01757, 42.14, -71.51 ---
--- 547, 01532, 42.31, -71.64 ---
--- 548, 01532, 42.31, -71.64 ---
--- 549, 02021, 42.15, -71.13 ---
--- 550, 02184, 42.2, -71.0 ---
--- 551, 02184, 42.2, -71.0 ---
--- 552, 02184, 42.2, -71.0 ---
--- 553, 01564, 42.43, -71.75 ---
--- 554, 01532, 42.31, -71.64 ---
--- 555, 02021, 42.15, -71.13 ---
--- 556, 02766, 41.96, -71.18 ---
--- 557, 01772, 42.3, -71.51 ---
--- 558, 01453, 42.51, -71.77 ---
--- 559, 01845, 42.7, -71.11 ---
--- 560, 01730, 42.48, -71.26 ---
--- 561, 02571, 41.76, -70.71 ---
--- 562, 01453, 42.51, -71.77 ---
--- 563, 02379, 42.01, -71.0 ---
--- 564, 02379, 42.01, -71.0 ---
--- 565, 02379, 42.01, -71.0 ---
--- 566, 01938, 42.67, -70.83 ---
--- 567, 01730, 42.48, -71.26 ---
--- 568, 01886, 42.58, -71.43 ---
--- 569, 01772, 42.3, -71.51 ---
--- 570, 01432, 42.56, -71.58 ---
--- 571, 01749, 42.39, -71.56 ---
--- 572, 02465, 42.35, -71.22 ---
--- 573, 01945, 42.5, -70.85 ---
--- 574, 02184, 42.2, -71.0 ---
--- 575, 02184, 42.2, -71.0 ---
--- 576, 02184, 42.2, -71.0 ---
--- 577, 01950, 42.81, -70.88 ---
--- 578, 01027, 42.26, -72.68 ---
--- 579, 01772, 42.3, -71.51 ---
--- 580, 01450, 42.6, -71.57 ---
--- 581, 01880, 42.5, -71.06 ---
--- 582, 02766, 41.96, -71.18 ---
--- 583, 01532, 42.31, -71.64 ---
--- 584, 01453, 42.51, -71.77 ---
--- 585, 02766, 41.96, -71.18 ---
--- 586, 01845, 42.7, -71.11 ---
--- 587, 01845, 42.7, -71.11 ---
--- 588, 01432, 42.56, -71.58 ---
--- 589, 01756, 42.1, -71.55 ---
--- 590, 01027, 42.26, -72.68 ---
--- 591, 01432, 42.56, -71.58 ---
--- 592, 02465, 42.35, -71.22 ---
--- 593, 01560, 42.17, -71.68 ---
--- 594, 01532, 42.31, -71.64 ---
--- 595, 01560, 42.17, -71.68 ---
--- 596, 01432, 42.56, -71.58 ---

# Get Zip, Longitude, Latitude from uszipcode using town/city name and state
- get zipcode with most population when there are multiple

In [ ]:
# current_residence_zip, current_res_long, current_res_lat

current_lat = [0 for i in range(len(df))]
current_lon = [0 for i in range(len(df))]

town_drop = [362, 510, 580, 704, 705, 706, 958, 1189, 1326, 1400, 1453]
town_missing = []

for i in range(len(df)):
  if i in town_drop:
    continue

  town_name = df['current_residence_town_city'][i]
  state_abbr = df['current_residence_state'][i]

  results = search.by_city_and_state(city=town_name, state=state_abbr, returns=0)

  if results:
    sorted_zips = sorted(
        results,
        key = lambda x : x.population if x.population is not None else -1,
        reverse = True
    )

    selected_zip = sorted_zips[0]

    zip_code = selected_zip.zipcode
    latitude = selected_zip.lat
    longitude = selected_zip.lng

    df.loc[i, 'current_residence_zip'] = zip_code
    current_lat[i] = latitude
    current_lon[i] = longitude

    print(f"--- {i}. {town_name}, {state_abbr} ({len(results)})---")
    print(f"ZIP: {zip_code} | Lat/Lon: {latitude}, {longitude}")

  else:
    print(f"'{i}, {town_name}, {state_abbr}' could not be find")
    town_missing.append(i)

print(town_missing)

df['current_lat'] = current_lat
df['current_lon'] = current_lon

/tmp/ipython-input-3779638770.py:31: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '02145' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[i, 'current_residence_zip'] = zip_code

--- 0. Somerville, MA (3)---
ZIP: 02145 | Lat/Lon: 42.39, -71.1
--- 1. Westford, MA (1)---
ZIP: 01886 | Lat/Lon: 42.58, -71.43
--- 2. Nashua, NH (4)---
ZIP: 03060 | Lat/Lon: 42.74, -71.46
--- 3. Waltham, MA (3)---
ZIP: 02453 | Lat/Lon: 42.37, -71.24
--- 4. Woburn, MA (1)---
ZIP: 01801 | Lat/Lon: 42.48, -71.15
--- 5. Burlington, MA (1)---
ZIP: 01803 | Lat/Lon: 42.5, -71.2
--- 6. Chelmsford, MA (1)---
ZIP: 01824 | Lat/Lon: 42.59, -71.36
--- 7. Taunton, MA (1)---
ZIP: 02780 | Lat/Lon: 41.9, -71.09
--- 8. Burlington, MA (1)---
ZIP: 01803 | Lat/Lon: 42.5, -71.2
--- 9. Woburn, MA (1)---
ZIP: 01801 | Lat/Lon: 42.48, -71.15
--- 10. Waltham, MA (3)---
ZIP: 02453 | Lat/Lon: 42.37, -71.24
--- 11. Beverly, MA (1)---
ZIP: 01915 | Lat/Lon: 42.57, -70.87
--- 12. Burlington, MA (1)---
ZIP: 01803 | Lat/Lon: 42.5, -71.2
--- 13. Lawrence, MA (3)---
ZIP: 01841 | Lat/Lon: 42.71, -71.16
--- 14. Woburn, MA (1)---
ZIP: 01801 | Lat/Lon: 42.48, -71.15
--- 15. Reading, MA (1)---
ZIP: 01867 | Lat/Lon: 42.53, -71.1
--- 16. Tyngsboro, MA (1)---
ZIP: 01879 | Lat/Lon: 42.68, -71.41
--- 17. Bedford, MA (1)---
ZIP: 01730 | Lat/Lon: 42.48, -71.26
--- 18. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26
--- 19. Lawrence, MA (3)---
ZIP: 01841 | Lat/Lon: 42.71, -71.16
--- 20. Ipswich, MA (1)---
ZIP: 01938 | Lat/Lon: 42.67, -70.83
--- 21. Ipswich, MA (1)---
ZIP: 01938 | Lat/Lon: 42.67, -70.83
--- 22. Middleborough, MA (1)---
ZIP: 02346 | Lat/Lon: 41.86, -70.9
--- 23. Stoneham, MA (1)---
ZIP: 02180 | Lat/Lon: 42.47, -71.09
--- 24. Somerville, MA (3)---
ZIP: 02145 | Lat/Lon: 42.39, -71.1
--- 25. Saugus, MA (1)---
ZIP: 01906 | Lat/Lon: 42.46, -71.01
--- 26. North Andover, MA (1)---
ZIP: 01845 | Lat/Lon: 42.7, -71.11
--- 27. Malden, MA (1)---
ZIP: 02148 | Lat/Lon: 42.43, -71.05
--- 28. Dracut, MA (1)---
ZIP: 01826 | Lat/Lon: 42.68, -71.3
--- 29. Lawrence, MA (3)---
ZIP: 01841 | Lat/Lon: 42.71, -71.16
--- 30. Dracut, MA (1)---
ZIP: 01826 | Lat/Lon: 42.68, -71.3
--- 31. Nashua, NH (4)---
ZIP: 03060 | Lat/Lon: 42.74, -71.46
--- 32. Cape Coral, FL (6)---
ZIP: 33914 | Lat/Lon: 26.55, -82.02
--- 33. Topsfield, MA (1)---
ZIP: 01983 | Lat/Lon: 42.63, -70.95
--- 34. Chester, NH (1)---
ZIP: 03036 | Lat/Lon: 42.95, -71.25
--- 35. North Reading, MA (1)---
ZIP: 01864 | Lat/Lon: 42.58, -71.08
--- 36. Andover, MA (1)---
ZIP: 01810 | Lat/Lon: 42.65, -71.14
--- 37. Revere, MA (1)---
ZIP: 02151 | Lat/Lon: 42.41, -70.99
--- 38. Bellingham, MA (1)---
ZIP: 02019 | Lat/Lon: 42.09, -71.47
--- 39. North Attleborough, MA (1)---
ZIP: 02760 | Lat/Lon: 41.97, -71.33
--- 40. Plainville, MA (1)---
ZIP: 02762 | Lat/Lon: 42.0, -71.33
--- 41. Medway, MA (1)---
ZIP: 02053 | Lat/Lon: 42.16, -71.43
--- 42. Medway, MA (1)---
ZIP: 02053 | Lat/Lon: 42.16, -71.43
--- 43. Uxbridge, MA (1)---
ZIP: 01569 | Lat/Lon: 42.08, -71.6
--- 44. Medway, MA (1)---
ZIP: 02053 | Lat/Lon: 42.16, -71.43
--- 45. Franklin, MA (1)---
ZIP: 02038 | Lat/Lon: 42.08, -71.38
--- 46. Ashland, MA (1)---
ZIP: 01721 | Lat/Lon: 42.25, -71.46
--- 47. Newburyport, MA (1)---
ZIP: 01950 | Lat/Lon: 42.81, -70.88
--- 48. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26
--- 49. Dracut, MA (1)---
ZIP: 01826 | Lat/Lon: 42.68, -71.3
--- 50. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26
--- 51. Watertown, MA (1)---
ZIP: 02472 | Lat/Lon: 42.37, -71.18
--- 52. Dorchester, MA (3)---
ZIP: 02125 | Lat/Lon: 42.32, -71.06
--- 53. Salem, MA (1)---
ZIP: 01970 | Lat/Lon: 42.51, -70.9
--- 54. Woburn, MA (1)---
ZIP: 01801 | Lat/Lon: 42.48, -71.15
--- 55. Stoughton, MA (1)---
ZIP: 02072 | Lat/Lon: 42.11, -71.1
--- 56. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13
--- 57. Hyde Park, MA (1)---
ZIP: 02136 | Lat/Lon: 42.26, -71.13
--- 58. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13
--- 59. North Attleborough, MA (1)---
ZIP: 02760 | Lat/Lon: 41.97, -71.33
--- 60. Quincy, MA (3)---
ZIP: 02169 | Lat/Lon: 42.26, -71.0
--- 61. Hyde Park, MA (1)---
ZIP: 02136 | Lat/Lon: 42.26, -71.13
--- 62. Reading, MA (1)---
ZIP: 01867 | Lat/Lon: 42.53, -71.1
--- 63. Somerville, MA (3)---
ZIP: 02145 | Lat/Lon: 42.39, -71.1
--- 64. Andover, MA (1)---
ZIP: 01810 | Lat/Lon: 42.65, -71.14
--- 65. Woburn, MA (1)---
ZIP: 01801 | Lat/Lon: 42.48, -71.15
--- 66. Westminster, MA (1)---
ZIP: 01473 | Lat/Lon: 42.55, -71.9
--- 67. Everett, MA (1)---
ZIP: 02149 | Lat/Lon: 42.4, -71.05
--- 68. Peabody, MA (1)---
ZIP: 01960 | Lat/Lon: 42.53, -70.97
--- 69. Beverly, MA (1)---
ZIP: 01915 | Lat/Lon: 42.57, -70.87
--- 70. Beverly, MA (1)---
ZIP: 01915 | Lat/Lon: 42.57, -70.87
--- 71. Beverly, MA (1)---
ZIP: 01915 | Lat/Lon: 42.57, -70.87
--- 72. Lowell, MA (4)---
ZIP: 01852 | Lat/Lon: 42.63, -71.3
--- 73. Woburn, MA (1)---
ZIP: 01801 | Lat/Lon: 42.48, -71.15
--- 74. Woburn, MA (1)---
ZIP: 01801 | Lat/Lon: 42.48, -71.15
--- 75. Andover, MA (1)---
ZIP: 01810 | Lat/Lon: 42.65, -71.14
--- 76. Haverhill, MA (3)---
ZIP: 01830 | Lat/Lon: 42.78, -71.08
--- 77. Boston, MA (16)---
ZIP: 02115 | Lat/Lon: 42.34, -71.1
--- 78. Marblehead, MA (1)---
ZIP: 01945 | Lat/Lon: 42.5, -70.85
--- 79. Melrose, MA (1)---
ZIP: 02176 | Lat/Lon: 42.45, -71.05
--- 80. Beverly, MA (1)---
ZIP: 01915 | Lat/Lon: 42.57, -70.87
--- 81. Swampscott, MA (1)---
ZIP: 01907 | Lat/Lon: 42.47, -70.91
--- 82. Lowell, MA (4)---
ZIP: 01852 | Lat/Lon: 42.63, -71.3
--- 83. Wilmington, MA (1)---
ZIP: 01887 | Lat/Lon: 42.55, -71.16
--- 84. Andover, MA (1)---
ZIP: 01810 | Lat/Lon: 42.65, -71.14
--- 85. Arlington, MA (2)---
ZIP: 02474 | Lat/Lon: 42.42, -71.16
--- 86. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26
--- 87. Nashua, NH (4)---
ZIP: 03060 | Lat/Lon: 42.74, -71.46
--- 88. Tewksbury, MA (1)---
ZIP: 01876 | Lat/Lon: 42.61, -71.23
--- 89. Quincy, MA (3)---
ZIP: 02169 | Lat/Lon: 42.26, -71.0
--- 90. North Billerica, MA (1)---
ZIP: 01862 | Lat/Lon: 42.58, -71.3
--- 91. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26
--- 92. Roslindale, MA (1)---
ZIP: 02131 | Lat/Lon: 42.28, -71.13
--- 93. Medford, MA (1)---
ZIP: 02155 | Lat/Lon: 42.42, -71.1
--- 94. Foxboro, MA (1)---
ZIP: 02035 | Lat/Lon: 42.06, -71.24
--- 95. West Roxbury, MA (1)---
ZIP: 02132 | Lat/Lon: 42.28, -71.16
--- 96. Norwood, MA (1)---
ZIP: 02062 | Lat/Lon: 42.18, -71.19
--- 97. Quincy, MA (3)---
ZIP: 02169 | Lat/Lon: 42.26, -71.0
--- 98. Dedham, MA (1)---
ZIP: 02026 | Lat/Lon: 42.24, -71.17
--- 99. Worcester, MA (10)---
ZIP: 01604 | Lat/Lon: 42.25, -71.77
--- 100. Quincy, MA (3)---
ZIP: 02169 | Lat/Lon: 42.26, -71.0
--- 101. Brookline, MA (2)---
ZIP: 02446 | Lat/Lon: 42.34, -71.12
--- 102. Quincy, MA (3)---
ZIP: 02169 | Lat/Lon: 42.26, -71.0
--- 103. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13
--- 104. Taunton, MA (1)---
ZIP: 02780 | Lat/Lon: 41.9, -71.09
--- 105. Hyde Park, MA (1)---
ZIP: 02136 | Lat/Lon: 42.26, -71.13
--- 106. Dedham, MA (1)---
ZIP: 02026 | Lat/Lon: 42.24, -71.17
--- 107. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13
--- 108. Randolph, MA (1)---
ZIP: 02368 | Lat/Lon: 42.17, -71.05
--- 109. Braintree, MA (1)---
ZIP: 02184 | Lat/Lon: 42.2, -71.0
--- 110. Quincy, MA (3)---
ZIP: 02169 | Lat/Lon: 42.26, -71.0
--- 111. Boston, MA (16)---
ZIP: 02115 | Lat/Lon: 42.34, -71.1
--- 112. Hyde Park, MA (1)---
ZIP: 02136 | Lat/Lon: 42.26, -71.13
--- 113. Lowell, MA (4)---
ZIP: 01852 | Lat/Lon: 42.63, -71.3
--- 114. Salem, MA (1)---
ZIP: 01970 | Lat/Lon: 42.51, -70.9
--- 115. Andover, MA (1)---
ZIP: 01810 | Lat/Lon: 42.65, -71.14
--- 116. Lowell, MA (4)---
ZIP: 01852 | Lat/Lon: 42.63, -71.3
--- 117. Methuen, MA (1)---
ZIP: 01844 | Lat/Lon: 42.74, -71.18
--- 118. Andover, MA (1)---
ZIP: 01810 | Lat/Lon: 42.65, -71.14
--- 119. Haverhill, MA (3)---
ZIP: 01830 | Lat/Lon: 42.78, -71.08
--- 120. Revere, MA (1)---
ZIP: 02151 | Lat/Lon: 42.41, -70.99
--- 121. Haverhill, MA (3)---
ZIP: 01830 | Lat/Lon: 42.78, -71.08
--- 122. Salem, MA (1)---
ZIP: 01970 | Lat/Lon: 42.51, -70.9
--- 123. Acton, MA (2)---
ZIP: 01720 | Lat/Lon: 42.48, -71.46
--- 124. Malden, MA (1)---
ZIP: 02148 | Lat/Lon: 42.43, -71.05
--- 125. Melrose, MA (1)---
ZIP: 02176 | Lat/Lon: 42.45, -71.05
--- 126. Brighton, MA (1)---
ZIP: 02135 | Lat/Lon: 42.35, -71.15
--- 127. Brookline, MA (2)---
ZIP: 02446 | Lat/Lon: 42.34, -71.12
--- 128. West Roxbury, MA (1)---
ZIP: 02132 | Lat/Lon: 42.28, -71.16
--- 129. Medford, MA (1)---
ZIP: 02155 | Lat/Lon: 42.42, -71.1
--- 130. Lynn, MA (4)---
ZIP: 01902 | Lat/Lon: 42.47, -70.94
--- 131. Revere, MA (1)---
ZIP: 02151 | Lat/Lon: 42.41, -70.99
--- 132. Andover, MA (1)---
ZIP: 01810 | Lat/Lon: 42.65, -71.14
--- 133. Tyngsboro, MA (1)---
ZIP: 01879 | Lat/Lon: 42.68, -71.41
--- 134. Billerica, MA (1)---
ZIP: 01821 | Lat/Lon: 42.55, -71.26
--- 135. Tewksbury, MA (1)---
ZIP: 01876 | Lat/Lon: 42.61, -71.23
--- 136. Lynn, MA (4)---
ZIP: 01902 | Lat/Lon: 42.47, -70.94
--- 137. Amherst, MA (2)---
ZIP: 01002 | Lat/Lon: 42.37, -72.52
--- 138. Stow, MA (1)---
ZIP: 01775 | Lat/Lon: 42.43, -71.5
--- 139. Boston, MA (16)---
ZIP: 02115 | Lat/Lon: 42.34, -71.1
--- 140. Easthampton, MA (1)---
ZIP: 01027 | Lat/Lon: 42.26, -72.68
--- 141. Raynham, MA (1)---
ZIP: 02767 | Lat/Lon: 41.93, -71.04
--- 142. Boston, MA (16)---
ZIP: 02115 | Lat/Lon: 42.34, -71.1
--- 143. Tyngsboro, MA (1)---
ZIP: 01879 | Lat/Lon: 42.68, -71.41
--- 144. Haverhill, MA (3)---
ZIP: 01830 | Lat/Lon: 42.78, -71.08
--- 145. Wilmington, MA (1)---
ZIP: 01887 | Lat/Lon: 42.55, -71.16
--- 146. Boxford, MA (1)---
ZIP: 01921 | Lat/Lon: 42.67, -70.98
--- 147. Arlington, MA (2)---
ZIP: 02474 | Lat/Lon: 42.42, -71.16
--- 148. Kensington, NH (1)---
ZIP: 03442 | Lat/Lon: 43.0, -71.93
--- 149. Tewksbury, MA (1)---
ZIP: 01876 | Lat/Lon: 42.61, -71.23
--- 150. Townsend, MA (1)---
ZIP: 01469 | Lat/Lon: 42.66, -71.7
--- 151. Byfield, MA (1)---
ZIP: 01922 | Lat/Lon: 42.75, -70.93
--- 152. Beverly, MA (1)---
ZIP: 01915 | Lat/Lon: 42.57, -70.87
--- 153. Boston, MA (16)---
ZIP: 02115 | Lat/Lon: 42.34, -71.1
--- 154. Plaistow, NH (1)---
ZIP: 03865 | Lat/Lon: 42.83, -71.09
--- 155. Lawrence, MA (3)---
ZIP: 01841 | Lat/Lon: 42.71, -71.16
--- 156. Georgetown, MA (1)---
ZIP: 01833 | Lat/Lon: 42.73, -70.98
--- 157. Lynn, MA (4)---
ZIP: 01902 | Lat/Lon: 42.47, -70.94
--- 158. Amesbury, MA (1)---
ZIP: 01913 | Lat/Lon: 42.85, -70.92
--- 159. Newburyport, MA (1)---
ZIP: 01950 | Lat/Lon: 42.81, -70.88
--- 160. Haverhill, MA (3)---
ZIP: 01830 | Lat/Lon: 42.78, -71.08
--- 161. Salisbury, MA (1)---
ZIP: 01952 | Lat/Lon: 42.83, -70.84
--- 162. Nashua, NH (4)---
ZIP: 03060 | Lat/Lon: 42.74, -71.46
--- 163. Amesbury, MA (1)---
ZIP: 01913 | Lat/Lon: 42.85, -70.92
--- 164. Saugus, MA (1)---
ZIP: 01906 | Lat/Lon: 42.46, -71.01
--- 165. Nashua, NH (4)---
ZIP: 03060 | Lat/Lon: 42.74, -71.46
--- 166. Beverly, MA (1)---
ZIP: 01915 | Lat/Lon: 42.57, -70.87
--- 167. Saugus, MA (1)---
ZIP: 01906 | Lat/Lon: 42.46, -71.01
--- 168. East Boston, MA (1)---
ZIP: 02128 | Lat/Lon: 42.36, -71.01
--- 169. Malden, MA (1)---
ZIP: 02148 | Lat/Lon: 42.43, -71.05
--- 170. Andover, MA (1)---
ZIP: 01810 | Lat/Lon: 42.65, -71.14
--- 171. Revere, MA (1)---
ZIP: 02151 | Lat/Lon: 42.41, -70.99
--- 172. Medway, MA (1)---
ZIP: 02053 | Lat/Lon: 42.16, -71.43
--- 173. Brighton, MA (1)---
ZIP: 02135 | Lat/Lon: 42.35, -71.15
--- 174. Saugus, MA (1)---
ZIP: 01906 | Lat/Lon: 42.46, -71.01
--- 175. Lowell, MA (4)---
ZIP: 01852 | Lat/Lon: 42.63, -71.3
--- 176. Uxbridge, MA (1)---
ZIP: 01569 | Lat/Lon: 42.08, -71.6
--- 177. Medway, MA (1)---
ZIP: 02053 | Lat/Lon: 42.16, -71.43
--- 178. Cambridge, MA (5)---
ZIP: 02139 | Lat/Lon: 42.37, -71.11
--- 179. Milford, MA (1)---
ZIP: 01757 | Lat/Lon: 42.14, -71.51
--- 180. Holliston, MA (1)---
ZIP: 01746 | Lat/Lon: 42.2, -71.43
--- 181. East Walpole, MA (1)---
ZIP: 02032 | Lat/Lon: 42.15, -71.21
--- 182. Quincy, MA (3)---
ZIP: 02169 | Lat/Lon: 42.26, -71.0
--- 183. Uxbridge, MA (1)---
ZIP: 01569 | Lat/Lon: 42.08, -71.6
--- 184. Milford, MA (1)---
ZIP: 01757 | Lat/Lon: 42.14, -71.51
--- 185. Franklin, MA (1)---
ZIP: 02038 | Lat/Lon: 42.08, -71.38
--- 186. Natick, MA (1)---
ZIP: 01760 | Lat/Lon: 42.28, -71.35
--- 187. Avon, MA (1)---
ZIP: 02322 | Lat/Lon: 42.13, -71.05
--- 188. Ashland, MA (1)---
ZIP: 01721 | Lat/Lon: 42.25, -71.46
--- 189. Weymouth, MA (1)---
ZIP: 02188 | Lat/Lon: 42.2, -70.96
--- 190. Mansfield, MA (1)---
ZIP: 02048 | Lat/Lon: 42.02, -71.21
--- 191. Lynn, MA (4)---
ZIP: 01902 | Lat/Lon: 42.47, -70.94
--- 192. Westborough, MA (1)---
ZIP: 01581 | Lat/Lon: 42.26, -71.61
--- 193. Methuen, MA (1)---
ZIP: 01844 | Lat/Lon: 42.74, -71.18
--- 194. Wrentham, MA (1)---
ZIP: 02093 | Lat/Lon: 42.06, -71.33
--- 195. Norwood, MA (1)---
ZIP: 02062 | Lat/Lon: 42.18, -71.19
--- 196. Taunton, MA (1)---
ZIP: 02780 | Lat/Lon: 41.9, -71.09
--- 197. Framingham, MA (2)---
ZIP: 01702 | Lat/Lon: 42.28, -71.44
--- 198. Medway, MA (1)---
ZIP: 02053 | Lat/Lon: 42.16, -71.43
--- 199. Plainville, MA (1)---
ZIP: 02762 | Lat/Lon: 42.0, -71.33
--- 200. Somerville, MA (3)---
ZIP: 02145 | Lat/Lon: 42.39, -71.1
--- 201. Medway, MA (1)---
ZIP: 02053 | Lat/Lon: 42.16, -71.43
--- 202. New Bedford, MA (4)---
ZIP: 02740 | Lat/Lon: 41.64, -70.94
--- 203. Millis, MA (1)---
ZIP: 02054 | Lat/Lon: 42.16, -71.35
--- 204. Norfolk, MA (1)---
ZIP: 02056 | Lat/Lon: 42.11, -71.31
--- 205. Mendon, MA (1)---
ZIP: 01756 | Lat/Lon: 42.1, -71.55
--- 206. Millis, MA (1)---
ZIP: 02054 | Lat/Lon: 42.16, -71.35
--- 207. Medway, MA (1)---
ZIP: 02053 | Lat/Lon: 42.16, -71.43
--- 208. Medway, MA (1)---
ZIP: 02053 | Lat/Lon: 42.16, -71.43
--- 209. Mendon, MA (1)---
ZIP: 01756 | Lat/Lon: 42.1, -71.55
--- 210. Fall River, MA (4)---
ZIP: 02720 | Lat/Lon: 41.73, -71.12
--- 211. Hopkinton, MA (1)---
ZIP: 01748 | Lat/Lon: 42.22, -71.52
--- 212. Franklin, MA (1)---
ZIP: 02038 | Lat/Lon: 42.08, -71.38
--- 213. East Taunton, MA (1)---
ZIP: 02718 | Lat/Lon: 41.87, -71.01
--- 214. Holliston, MA (1)---
ZIP: 01746 | Lat/Lon: 42.2, -71.43
--- 215. Medfield, MA (1)---
ZIP: 02052 | Lat/Lon: 42.18, -71.3
--- 216. Hopkinton, MA (1)---
ZIP: 01748 | Lat/Lon: 42.22, -71.52
--- 217. Natick, MA (1)---
ZIP: 01760 | Lat/Lon: 42.28, -71.35
--- 218. Franklin, MA (1)---
ZIP: 02038 | Lat/Lon: 42.08, -71.38
--- 219. Natick, MA (1)---
ZIP: 01760 | Lat/Lon: 42.28, -71.35
--- 220. Brighton, MA (1)---
ZIP: 02135 | Lat/Lon: 42.35, -71.15
--- 221. Milford, MA (1)---
ZIP: 01757 | Lat/Lon: 42.14, -71.51
--- 222. Hopkinton, MA (1)---
ZIP: 01748 | Lat/Lon: 42.22, -71.52
--- 223. Medway, MA (1)---
ZIP: 02053 | Lat/Lon: 42.16, -71.43
--- 224. Shrewsbury, MA (1)---
ZIP: 01545 | Lat/Lon: 42.3, -71.71
--- 225. Marlborough, MA (1)---
ZIP: 01752 | Lat/Lon: 42.34, -71.54
--- 226. Bridgewater, MA (1)---
ZIP: 02324 | Lat/Lon: 41.98, -70.97
--- 227. Providence, RI (7)---
ZIP: 02909 | Lat/Lon: 41.82, -71.45
--- 228. Woonsocket, RI (1)---
ZIP: 02895 | Lat/Lon: 41.99, -71.5
--- 229. Middleborough, MA (1)---
ZIP: 02346 | Lat/Lon: 41.86, -70.9
--- 230. Franklin, MA (1)---
ZIP: 02038 | Lat/Lon: 42.08, -71.38
--- 231. Lowell, MA (4)---
ZIP: 01852 | Lat/Lon: 42.63, -71.3
--- 232. Taunton, MA (1)---
ZIP: 02780 | Lat/Lon: 41.9, -71.09
--- 233. Medfield, MA (1)---
ZIP: 02052 | Lat/Lon: 42.18, -71.3
--- 234. Holliston, MA (1)---
ZIP: 01746 | Lat/Lon: 42.2, -71.43
--- 235. Northborough, MA (1)---
ZIP: 01532 | Lat/Lon: 42.31, -71.64
--- 236. North Attleborough, MA (1)---
ZIP: 02760 | Lat/Lon: 41.97, -71.33
--- 237. Medford, MA (1)---
ZIP: 02155 | Lat/Lon: 42.42, -71.1
--- 238. Marshfield, MA (1)---
ZIP: 02050 | Lat/Lon: 42.09, -70.7
--- 239. Hudson, MA (1)---
ZIP: 01749 | Lat/Lon: 42.39, -71.56
--- 240. Bellingham, MA (1)---
ZIP: 02019 | Lat/Lon: 42.09, -71.47
--- 241. Bellingham, MA (1)---
ZIP: 02019 | Lat/Lon: 42.09, -71.47
--- 242. East Walpole, MA (1)---
ZIP: 02032 | Lat/Lon: 42.15, -71.21
--- 243. Somerville, MA (3)---
ZIP: 02145 | Lat/Lon: 42.39, -71.1
--- 244. Whitinsville, MA (1)---
ZIP: 01588 | Lat/Lon: 42.11, -71.67
--- 245. Cambridge, MA (5)---
ZIP: 02139 | Lat/Lon: 42.37, -71.11
--- 246. Dorchester, MA (3)---
ZIP: 02125 | Lat/Lon: 42.32, -71.06
--- 247. Brockton, MA (2)---
ZIP: 02301 | Lat/Lon: 42.08, -71.02
--- 248. Malden, MA (1)---
ZIP: 02148 | Lat/Lon: 42.43, -71.05
--- 249. Quincy, MA (3)---
ZIP: 02169 | Lat/Lon: 42.26, -71.0
--- 250. Brighton, MA (1)---
ZIP: 02135 | Lat/Lon: 42.35, -71.15
--- 251. Waltham, MA (3)---
ZIP: 02453 | Lat/Lon: 42.37, -71.24
--- 252. Roxbury, MA (1)---
ZIP: 02119 | Lat/Lon: 42.32, -71.09
--- 253. Malden, MA (1)---
ZIP: 02148 | Lat/Lon: 42.43, -71.05
--- 254. Stoughton, MA (1)---
ZIP: 02072 | Lat/Lon: 42.11, -71.1
--- 255. Malden, MA (1)---
ZIP: 02148 | Lat/Lon: 42.43, -71.05
--- 256. Scituate, MA (1)---
ZIP: 02066 | Lat/Lon: 42.18, -70.73
--- 257. Holbrook, MA (1)---
ZIP: 02343 | Lat/Lon: 42.14, -71.0
--- 258. Brockton, MA (2)---
ZIP: 02301 | Lat/Lon: 42.08, -71.02
--- 259. Newtonville, MA (1)---
ZIP: 02460 | Lat/Lon: 42.35, -71.2
--- 260. Newtonville, MA (1)---
ZIP: 02460 | Lat/Lon: 42.35, -71.2
--- 261. Boston, MA (16)---
ZIP: 02115 | Lat/Lon: 42.34, -71.1
--- 262. Hyde Park, MA (1)---
ZIP: 02136 | Lat/Lon: 42.26, -71.13
--- 263. Haverhill, MA (3)---
ZIP: 01830 | Lat/Lon: 42.78, -71.08
--- 264. Worcester, MA (10)---
ZIP: 01604 | Lat/Lon: 42.25, -71.77
'265, Oak Bluffs, MA' could not be find
--- 266. North Reading, MA (1)---
ZIP: 01864 | Lat/Lon: 42.58, -71.08
--- 267. Marlborough, MA (1)---
ZIP: 01752 | Lat/Lon: 42.34, -71.54
--- 268. Lynnfield, MA (1)---
ZIP: 01940 | Lat/Lon: 42.53, -71.04
--- 269. Abington, MA (1)---
ZIP: 02351 | Lat/Lon: 42.11, -70.95
--- 270. Methuen, MA (1)---
ZIP: 01844 | Lat/Lon: 42.74, -71.18
--- 271. Worcester, MA (10)---
ZIP: 01604 | Lat/Lon: 42.25, -71.77
--- 272. Quincy, MA (3)---
ZIP: 02169 | Lat/Lon: 42.26, -71.0
--- 273. Clinton, MA (1)---
ZIP: 01510 | Lat/Lon: 42.41, -71.68
--- 274. Clinton, MA (1)---
ZIP: 01510 | Lat/Lon: 42.41, -71.68
--- 275. Lawrence, MA (3)---
ZIP: 01841 | Lat/Lon: 42.71, -71.16
--- 276. Lawrence, MA (3)---
ZIP: 01841 | Lat/Lon: 42.71, -71.16
--- 277. Weymouth, MA (1)---
ZIP: 02188 | Lat/Lon: 42.2, -70.96
--- 278. Weymouth, MA (1)---
ZIP: 02188 | Lat/Lon: 42.2, -70.96
--- 279. Weymouth, MA (1)---
ZIP: 02188 | Lat/Lon: 42.2, -70.96
--- 280. Seekonk, MA (1)---
ZIP: 02771 | Lat/Lon: 41.81, -71.33
--- 281. Seekonk, MA (1)---
ZIP: 02771 | Lat/Lon: 41.81, -71.33
--- 282. Newton, MA (1)---
ZIP: 02458 | Lat/Lon: 42.35, -71.19
--- 283. Newton, MA (1)---
ZIP: 02458 | Lat/Lon: 42.35, -71.19
--- 284. Framingham, MA (2)---
ZIP: 01702 | Lat/Lon: 42.28, -71.44
--- 285. Yarmouth Port, MA (1)---
ZIP: 02675 | Lat/Lon: 41.7, -70.22
--- 286. West Dennis, MA (1)---
ZIP: 02670 | Lat/Lon: 41.66, -70.16
--- 287. Framingham, MA (2)---
ZIP: 01702 | Lat/Lon: 42.28, -71.44
--- 288. Lowell, MA (4)---
ZIP: 01852 | Lat/Lon: 42.63, -71.3
--- 289. Acton, MA (2)---
ZIP: 01720 | Lat/Lon: 42.48, -71.46
--- 290. Woburn, MA (1)---
ZIP: 01801 | Lat/Lon: 42.48, -71.15
--- 291. Milford, MA (1)---
ZIP: 01757 | Lat/Lon: 42.14, -71.51
--- 292. Milford, MA (1)---
ZIP: 01757 | Lat/Lon: 42.14, -71.51
--- 293. Southborough, MA (1)---
ZIP: 01772 | Lat/Lon: 42.3, -71.51
--- 294. Hopedale, MA (1)---
ZIP: 01747 | Lat/Lon: 42.12, -71.54
--- 295. Salem, MA (1)---
ZIP: 01970 | Lat/Lon: 42.51, -70.9
--- 296. Englewood, FL (2)---
ZIP: 34223 | Lat/Lon: 26.95, -82.35
--- 297. Quincy, MA (3)---
ZIP: 02169 | Lat/Lon: 42.26, -71.0
--- 298. Methuen, MA (1)---
ZIP: 01844 | Lat/Lon: 42.74, -71.18
--- 299. North Grafton, MA (1)---
ZIP: 01536 | Lat/Lon: 42.23, -71.69
--- 300. North Grafton, MA (1)---
ZIP: 01536 | Lat/Lon: 42.23, -71.69
--- 301. Northborough, MA (1)---
ZIP: 01532 | Lat/Lon: 42.31, -71.64
--- 302. Fitchburg, MA (1)---
ZIP: 01420 | Lat/Lon: 42.58, -71.81
--- 303. Dorchester, MA (3)---
ZIP: 02125 | Lat/Lon: 42.32, -71.06
--- 304. Rockland, MA (1)---
ZIP: 02370 | Lat/Lon: 42.13, -70.91
--- 305. Mansfield, MA (1)---
ZIP: 02048 | Lat/Lon: 42.02, -71.21
--- 306. Norwood, MA (1)---
ZIP: 02062 | Lat/Lon: 42.18, -71.19
--- 307. Shrewsbury, MA (1)---
ZIP: 01545 | Lat/Lon: 42.3, -71.71
--- 308. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13
--- 309. Canton, MA (1)---
ZIP: 02021 | Lat/Lon: 42.15, -71.13
--- 310. Canton, MA (1)---

- handling missing town/city name by manually

In [ ]:
need_handle = town_drop + town_missing
print(need_handle)

for i in range(len(df)):
  if i in need_handle:
    print(df['current_residence_town_city'][i], df['current_residence_state'][i])

# Oak Bluffs MA: 02557 / 41.44 / -70.56
# Pelham MA: 01002 / 42.43 / -72.47
# Nashua MA: 03060 / 42.74 / -71.45
# Easton MA: 02356 / 42.06 / -71.11
# East Providence MA: 02914 / 41.81 / -71.38
# Woodstock MA: 06281 / 41.89 / -71.94
# Woonsocket MA: 02895 / 42.00 / -71.50
# Menomonie WI: 54751 / 44.88 / -91.96
# Hooksett NH: 03106 / 43.09 / -71.46
# Bristol MA: 02780 / 41.63 / -70.92

[362, 510, 580, 704, 705, 706, 958, 1189, 1326, 1400, 1453, 265, 336, 343, 602, 608, 737, 746, 938, 1230, 1345]
Oak Bluffs MA
Oak Bluffs MA
Oak Bluffs MA
Pelham MA
Nashua MA
Nashua MA
Easton MA
East Providence MA
Woodstock MA
Woodstock MA
Woodstock MA
Oak Bluffs MA
Easton MA
Oak Bluffs MA
Woonsocket MA
Menomonie MA
Hooksett MA
Nashua MA
Oak Bluffs MA
Nashua MA
Bristol MA

In [ ]:
for i in range(len(df)):
  if df['current_residence_town_city'][i] == 'Oak Bluffs':
    df.loc[i, 'current_residence_zip'] = '02557'
    df.loc[i, 'current_lat'] = 41.44
    df.loc[i, 'current_lon'] = -70.56
  if df['current_residence_town_city'][i] == 'Pelham':
    df.loc[i, 'current_residence_zip'] = '01002'
    df.loc[i, 'current_lat'] = 42.43
    df.loc[i, 'current_lon'] = -72.47
  elif df['current_residence_town_city'][i] == 'Nashua':
    df.loc[i, 'current_residence_zip'] = '03060'
    df.loc[i, 'current_lat'] = 42.74
    df.loc[i, 'current_lon'] = -71.45
  elif df['current_residence_town_city'][i] == 'Easton':
    df.loc[i, 'current_residence_zip'] = '02356'
    df.loc[i, 'current_lat'] = 42.06
    df.loc[i, 'current_lon'] = -71.11
  elif df['current_residence_town_city'][i] == 'East Providence':
    df.loc[i, 'current_residence_zip'] = '02914'
    df.loc[i, 'current_lat'] = 41.81
    df.loc[i, 'current_lon'] = -71.38
  elif df['current_residence_town_city'][i] == 'Woodstock':
    df.loc[i, 'current_residence_zip'] = '06281'
    df.loc[i, 'current_lat'] = 41.89
    df.loc[i, 'current_lon'] = -71.94
  elif df['current_residence_town_city'][i] ==  'Woonsocket':
    df.loc[i, 'current_residence_zip'] = '02895'
    df.loc[i, 'current_lat'] = 42.0
    df.loc[i, 'current_lon'] = -71.5
  elif df['current_residence_town_city'][i] == 'Menomonie':
    df.loc[i, 'current_residence_state'] = 'WI'
    df.loc[i, 'current_residence_zip'] = '54751'
    df.loc[i, 'current_lat'] = 44.88
    df.loc[i, 'current_lon'] = -91.96
  elif df['current_residence_town_city'][i] == 'Hooksett':
    df.loc[i, 'current_residence_state'] = 'NH'
    df.loc[i, 'current_residence_zip'] = '03106'
    df.loc[i, 'current_lat'] = 43.09
    df.loc[i, 'current_lon'] = -71.46
  elif df['current_residence_town_city'][i] == 'Bristol':
    df.loc[i, 'current_residence_zip'] = '02780'
    df.loc[i, 'current_lat'] = 41.63
    df.loc[i, 'current_lon'] = -70.92

# Calculate the distance between property and current residence using Longitude and Latitude

In [ ]:
# distance
from geopy.distance import geodesic

distance_km = [0 for i in range(len(df))]
distance_mi = [0 for i in range(len(df))]

for i in range(len(df)):
  coords_1 = (df['property_lat'][i], df['property_lon'][i])
  coords_2 = (df['current_lat'][i], df['current_lon'][i])

  dist_km = geodesic(coords_1, coords_2).km
  distance_km[i] = dist_km

  dist_miles = geodesic(coords_1, coords_2).miles
  distance_mi[i] = dist_miles

df['distance_km'] = distance_km
df['distance_mi'] = distance_mi

In [ ]:
print(df['distance_km'].describe())
print(df['distance_mi'].describe())

count    1465.000000
mean       30.908066
std       121.956919
min         0.000000
25%         8.924493
50%        17.894311
75%        32.471481
max      2155.690737
Name: distance_km, dtype: float64
count    1465.000000
mean       19.205382
std        75.780516
min         0.000000
25%         5.545423
50%        11.119010
75%        20.176843
max      1339.484124
Name: distance_mi, dtype: float64

# Making dataframe that includes every counties in MA and each towns it contains

In [ ]:
# current_residence_county
df_county = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/county_town - Sheet1.csv')
print(df_county)

        county                                               town
0   Barnstable  Barnstable Town city, Bourne town, Brewster to...
1        Essex  Amesbury town, Beverly city, Danvers town, Ess...
2    Middlesex  Acton town, Arlington town, Ashby town, Ashlan...
3      Norfolk  Wilmington town, Winchester town, Woburn city,...
4     Plymouth  Carver town, Duxbury town, Hanover town, Hingh...
5      Suffolk  Boston city, Chelsea city, Revere city, Winthr...
6    Berkshire  Alford town, Becket town, Clarksburg town, Egr...
7      Bristol  Easton town, Raynham town, Acushnet town, Dart...
8     Franklin  Taunton city, Ashfield town, Bernardston town,...
9      Hampden  Agawam city, Blandford town, Brimfield town, C...
10   Hampshire  Amherst town, Belchertown town, Chesterfield t...
11   Worcester  Berlin town, Blackstone town, Bolton town, Har...
12       Dukes  Aquinnah town, Chilmark town, Edgartown town, ...
13   Nantucket  Oak Bluffs town, Tisbury town, West Tisbury to...

In [ ]:
df_clean = df_county.assign(town=df_county['town'].str.split(', ')).explode('town')
df_clean['town'] = df_clean['town'].str.replace(r' (city|City)$', '', regex=True).str.strip()
df_clean['town'] = df_clean['town'].str.replace(r' (Town|town)$', '', regex=True).str.strip()
df_final = df_clean[['county', 'town']].reset_index(drop=True)
print(df_final)

         county          town
0    Barnstable    Barnstable
1    Barnstable        Bourne
2    Barnstable      Brewster
3    Barnstable       Chatham
4    Barnstable        Dennis
..          ...           ...
339       Dukes
340   Nantucket    Oak Bluffs
341   Nantucket       Tisbury
342   Nantucket  West Tisbury
343   Nantucket     Nantucket

[344 rows x 2 columns]

# Mapping county using town/city name of property/current

In [ ]:
county_map = df_final[['town', 'county']].drop_duplicates()
county_map.columns = ['current_residence_town_city', 'current_county']
df = pd.merge(
    df,
    county_map,
    on='current_residence_town_city',
    how='left'
)

In [ ]:
# property county
county_map = df_final[['town', 'county']].drop_duplicates()
county_map.columns = ['property_town_city', 'property_county']
df = pd.merge(
    df,
    county_map,
    on='property_town_city',
    how='left'
)

# Make binary columns of local applicant

- local: if in the same county

In [ ]:
# local_applicant by same county
for i in range(len(df)):
  if df['property_county'][i] == df['current_county'][i]:
    df.loc[i, 'local_applicant_county'] = 1
  else:
    df.loc[i, 'local_applicant_county'] = 0

- local: if in the same town/city

In [ ]:
# local_applicant by same town/city
for i in range(len(df)):
  if df['property_town_city'][i] == df['current_residence_town_city'][i]:
    df.loc[i, 'local_applicant_town'] = 1
  else:
    df.loc[i, 'local_applicant_town'] = 0

- local: if distance between property and county is zero

In [ ]:
# local_applicant by zero distance
for i in range(len(df)):
  if df['distance_mi'][i] == 0:
    df.loc[i, 'local_applicant_distance'] = 1
  else:
    df.loc[i, 'local_applicant_distance'] = 0

In [ ]:
df

,id_number,submission_date,age,disability,chapa_races,census_races,current_residence_town_city,current_residence_state,current_residence_zip,application_source,...,property_lon,current_lat,current_lon,distance_km,distance_mi,current_county,property_county,local_applicant_county,local_applicant_town,local_applicant_distance
0,150733,2022-02-08,65,0,White/Non-Minority,White alone,Somerville,MA,02145,Unknown,...,-71.11,42.39,-71.10,34.445797,21.403626,Middlesex,Essex,0.0,0.0,0.0
1,439181,2022-02-08,59,0,Hispanic/Latino,Unknown,Westford,MA,01886,Unknown,...,-71.11,42.58,-71.43,29.436218,18.290818,Middlesex,Essex,0.0,0.0,0.0
2,226436,2022-02-08,60,0,White/Non-Minority,White alone,Nashua,NH,03060,Unknown,...,-71.11,42.74,-71.45,28.201723,17.523738,NaN,Essex,0.0,0.0,0.0
3,170029,2021-06-15,35,0,White/Non-Minority,White alone,Waltham,MA,02453,Unknown,...,-71.26,42.37,-71.24,12.329329,7.661090,Middlesex,Middlesex,1.0,0.0,0.0
4,569863,2021-06-15,38,0,Black or African American,Black or African American alone,Woburn,MA,01801,Unknown,...,-71.26,42.48,-71.15,9.044772,5.620161,Norfolk,Middlesex,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,995246,2024-05-19,47,0,White,White alone,Framingham,MA,01702,Friend/Word of Mouth,...,-71.51,42.28,-71.44,6.185841,3.843703,Middlesex,Worcester,0.0,0.0,0.0
1461,997147,2024-05-21,35,0,Choose not to answer,Missing,Marlborough,MA,01752,MyMassHome,...,-71.51,42.34,-71.54,5.085050,3.159703,Middlesex,Worcester,0.0,0.0,0.0
1462,997147,2024-06-21,35,0,Choose not to answer,Missing,Marlborough,MA,01752,MyMassHome,...,-71.22,42.34,-71.54,26.391924,16.399181,Middlesex,Middlesex,1.0,0.0,0.0
1463,998583,2024-05-09,25,0,"Black or African American, Hispanic or Latino",Black or African American,Bedford,MA,01730,MyMassHome,...,-71.51,42.48,-71.26,28.697616,17.831872,Middlesex,Worcester,0.0,0.0,0.0
1464,998583,2024-05-31,25,0,"Black or African American, Hispanic or Latino",Black or African American,Bedford,MA,01730,MyMassHome,...,-71.77,42.48,-71.26,42.057008,26.133013,Middlesex,Worcester,0.0,0.0,0.0

In [ ]:
df.to_csv("/content/drive/MyDrive/Colab Notebooks/40B_zip_long_lat.csv", index=False)

# Summary

1. Geocoding data

  The final preprocessed data was used to complete the geocoding data, preparing the answer for Question 1. The Latitude and Longitude values for each applicant were obtained using the external uszipcode module with the zip code, town/city, and state data.

  The distance between the two locations was calculated in miles using the Longitude and Latitude values for both the property and current locations. This established a basis for classifying an applicant's location change as either local or distant.


2. County mapping

  To move beyond simply classifying local vs. distant based on whether the town/city name is the same or different, an analysis was sought using the broader criterion of county change.

  A PDF file containing all Massachusetts (MA) counties and the town/city names included in each county was found, and a CSV file was manually created from it. This CSV file was used to create a county-town/city dataframe, which was then mapped with our data to extract the county information for each applicant's property and current locations.


3. local vs. distant categorize

  Local and distant were categorized based on a total of three criteria:
- Whether there was a county change.
- Whether there was a town/city change.
- Whether there was a mile distance change.

  Since the number of 'local' applicants varies depending on these three criteria, there is a need to establish a clearer standard. This will be finalized later through a client meeting.


4. Next step

Now that the geocoding data has been established, the focus will shift to analyzing the distribution and specific characteristics of demographic features based on the local vs. distant classification.